# @generated by ptfkit-codegen; DO NOT EDIT.
from __future__ import annotations

from typing import Any, cast

import pytest

from _helpers import prepare_vector_case
from ptfkit.ferrerjulia2004 import (
    calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand,
    calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_calcaric_regosol_sand,
    calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_calcic_cambisol_sand,
    calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_calcic_luvisol_sand,
    calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_campbell_shiozawa,
    calc_ptf_ferrerjulia2004_chromic_luvisol_sand,
    calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_cosby,
    calc_ptf_ferrerjulia2004_dane_puckett,
    calc_ptf_ferrerjulia2004_dystric_cambisol_sand,
    calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_dystric_regosol_sand,
    calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_eutric_cambisol_sand,
    calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_eutric_regosol_sand,
    calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_general_sand,
    calc_ptf_ferrerjulia2004_general_texture_organic_matter,
    calc_ptf_ferrerjulia2004_gleyic_cambisol_sand,
    calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_gleyic_luvisol_sand,
    calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_gleyic_solonchak_sand,
    calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter,
    calc_ptf_ferrerjulia2004_humic_acrisol_sand,
    calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_humic_cambisol_sand,
    calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_orthic_luvisol_sand,
    calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter,
    calc_ptf_ferrerjulia2004_puckett,
    calc_ptf_ferrerjulia2004_ranker_sand,
    calc_ptf_ferrerjulia2004_ranker_texture_organic_matter,
    calc_ptf_ferrerjulia2004_rendzina_sand,
    calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter,
    calc_ptf_ferrerjulia2004_saxton,
)


def assert_accepted(actual: object, acceptance: tuple[float, float, bool]):
    actual_float = float(cast('Any', actual))
    lower, upper, exact = acceptance
    assert actual_float == lower if exact else lower <= actual_float <= upper


CASES_CALC_PTF_FERRERJULIA2004_CAMPBELL_SHIOZAWA = [
    ({'clay': 25.0, 'sand': 50.0}, {'k_sat': (0.025071690110308728, 0.025071690110309172, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CAMPBELL_SHIOZAWA)
def test_calc_ptf_ferrerjulia2004_campbell_shiozawa_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_campbell_shiozawa(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_campbell_shiozawa_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_CAMPBELL_SHIOZAWA)
    result = calc_ptf_ferrerjulia2004_campbell_shiozawa(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_campbell_shiozawa_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_CAMPBELL_SHIOZAWA)
    result = calc_ptf_ferrerjulia2004_campbell_shiozawa(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_SAXTON = [
    (
        {'clay': 25.0, 'sand': 50.0},
        {'k_sat': (0.00022673430784327062, 0.0002267343078432741, False)},
    ),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_SAXTON)
def test_calc_ptf_ferrerjulia2004_saxton_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_saxton(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_saxton_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_SAXTON)
    result = calc_ptf_ferrerjulia2004_saxton(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_saxton_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_SAXTON)
    result = calc_ptf_ferrerjulia2004_saxton(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_DANE_PUCKETT = [
    ({'clay': 25.0}, {'k_sat': (8.302039828385258, 8.302039828385485, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_DANE_PUCKETT)
def test_calc_ptf_ferrerjulia2004_dane_puckett_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_dane_puckett(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dane_puckett_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_DANE_PUCKETT)
    result = calc_ptf_ferrerjulia2004_dane_puckett(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dane_puckett_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_DANE_PUCKETT)
    result = calc_ptf_ferrerjulia2004_dane_puckett(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_PUCKETT = [
    ({'clay': 25.0}, {'k_sat': (1.1257967371765512, 1.1257967371765796, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_PUCKETT)
def test_calc_ptf_ferrerjulia2004_puckett_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_puckett(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_puckett_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_PUCKETT)
    result = calc_ptf_ferrerjulia2004_puckett(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_puckett_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_PUCKETT)
    result = calc_ptf_ferrerjulia2004_puckett(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_COSBY = [
    ({'clay': 25.0, 'sand': 50.0}, {'k_sat': (26.09183097091871, 26.091830970919165, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_COSBY)
def test_calc_ptf_ferrerjulia2004_cosby_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_cosby(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_cosby_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_COSBY)
    result = calc_ptf_ferrerjulia2004_cosby(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_cosby_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_COSBY)
    result = calc_ptf_ferrerjulia2004_cosby(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (14.529879794648036, 14.529879794648263, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_humic_acrisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_humic_acrisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_acrisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_humic_acrisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_acrisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_SAND)
    result = calc_ptf_ferrerjulia2004_humic_acrisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (19.563474999999972, 19.56347500000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_ACRISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_humic_acrisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (9.995162000935132, 9.995162000935359, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_calcic_cambisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_cambisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_cambisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (16.51624999999997, 16.516250000000028, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcic_cambisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (13.413573870265756, 13.413573870265983, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_dystric_cambisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_cambisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_cambisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (20.78999999999997, 20.790000000000028, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_dystric_cambisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (11.570199173737253, 11.57019917373748, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_eutric_cambisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_cambisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_cambisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (19.52349999999997, 19.523500000000027, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_eutric_cambisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (6.559110321079869, 6.559110321079983, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (11.513999999999985, 11.514000000000014, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_cambisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (13.820129957492394, 13.820129957492622, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_humic_cambisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_humic_cambisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_cambisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_humic_cambisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_cambisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_humic_cambisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (20.90289999999997, 20.902900000000027, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_HUMIC_CAMBISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_humic_cambisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (10.959482760491262, 10.95948276049149, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (13.100999999999987, 13.101000000000015, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'),
    CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_TEXTURE_ORGANIC_MATTER,
)
def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_FLUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcaric_fluvisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (6.931067612606899, 6.931067612607013, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_calcic_luvisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_luvisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_luvisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (8.933199999999985, 8.933200000000014, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcic_luvisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (10.616557272778318, 10.616557272778545, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_chromic_luvisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_chromic_luvisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_chromic_luvisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (17.14649999999997, 17.146500000000028, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CHROMIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_chromic_luvisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (7.049012285884137, 7.049012285884251, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (19.549999999999972, 19.55000000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_luvisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (12.042809111804472, 12.042809111804699, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_SAND
)
def test_calc_ptf_ferrerjulia2004_orthic_luvisol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_orthic_luvisol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_orthic_luvisol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (21.404249999999973, 21.40425000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_ORTHIC_LUVISOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_orthic_luvisol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_RANKER_SAND = [
    ({'sand': 50.0}, {'k_sat': (12.423399456061821, 12.423399456062048, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_RANKER_SAND)
def test_calc_ptf_ferrerjulia2004_ranker_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_ranker_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_ranker_sand_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_RANKER_SAND)
    result = calc_ptf_ferrerjulia2004_ranker_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_ranker_sand_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_RANKER_SAND)
    result = calc_ptf_ferrerjulia2004_ranker_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_RANKER_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (22.45149999999997, 22.451500000000028, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_RANKER_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_ranker_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_ranker_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_ranker_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_RANKER_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_ranker_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_ranker_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_RANKER_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_ranker_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (12.26737473383298, 12.267374733833208, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_SAND
)
def test_calc_ptf_ferrerjulia2004_calcaric_regosol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_regosol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_regosol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (20.53199999999997, 20.53200000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_CALCARIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_calcaric_regosol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (12.08140131318308, 12.081401313183308, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_SAND
)
def test_calc_ptf_ferrerjulia2004_dystric_regosol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_dystric_regosol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_regosol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_dystric_regosol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_regosol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_dystric_regosol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (17.133499999999973, 17.13350000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_DYSTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_dystric_regosol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_SAND = [
    ({'sand': 50.0}, {'k_sat': (13.674049986082617, 13.674049986082844, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_SAND
)
def test_calc_ptf_ferrerjulia2004_eutric_regosol_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_eutric_regosol_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_regosol_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_eutric_regosol_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_regosol_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_SAND
    )
    result = calc_ptf_ferrerjulia2004_eutric_regosol_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (24.06374999999997, 24.063750000000027, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_EUTRIC_REGOSOL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_eutric_regosol_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_SAND = [
    ({'sand': 50.0}, {'k_sat': (12.515763717130197, 12.515763717130424, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_SAND)
def test_calc_ptf_ferrerjulia2004_rendzina_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_rendzina_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_rendzina_sand_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_SAND)
    result = calc_ptf_ferrerjulia2004_rendzina_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_rendzina_sand_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_SAND)
    result = calc_ptf_ferrerjulia2004_rendzina_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (16.290499999999973, 16.29050000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_RENDZINA_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_rendzina_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_SAND = [
    ({'sand': 50.0}, {'k_sat': (4.883324693640371, 4.883324693640485, False)}),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_SAND
)
def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_sand_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_sand_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_SAND
    )
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (10.535829999999986, 10.535830000000015, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GLEYIC_SOLONCHAK_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_gleyic_solonchak_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GENERAL_SAND = [
    ({'sand': 50.0}, {'k_sat': (10.714718864968997, 10.714718864969225, False)}),
]


@pytest.mark.parametrize(('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GENERAL_SAND)
def test_calc_ptf_ferrerjulia2004_general_sand_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_general_sand(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_general_sand_array():
    inputs, acceptance, _out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_GENERAL_SAND)
    result = calc_ptf_ferrerjulia2004_general_sand(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_general_sand_out():
    inputs, acceptance, out = prepare_vector_case(CASES_CALC_PTF_FERRERJULIA2004_GENERAL_SAND)
    result = calc_ptf_ferrerjulia2004_general_sand(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])


CASES_CALC_PTF_FERRERJULIA2004_GENERAL_TEXTURE_ORGANIC_MATTER = [
    (
        {'clay': 25.0, 'organic_matter': 2.5, 'sand': 50.0},
        {'k_sat': (20.06324999999997, 20.06325000000003, False)},
    ),
]


@pytest.mark.parametrize(
    ('inputs', 'acceptance'), CASES_CALC_PTF_FERRERJULIA2004_GENERAL_TEXTURE_ORGANIC_MATTER
)
def test_calc_ptf_ferrerjulia2004_general_texture_organic_matter_golden(
    inputs: dict[str, float], acceptance: dict[str, tuple[float, float, bool]]
):
    result = calc_ptf_ferrerjulia2004_general_texture_organic_matter(**inputs)

    assert_accepted(result, acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_general_texture_organic_matter_array():
    inputs, acceptance, _out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GENERAL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_general_texture_organic_matter(**inputs, out=None)
    assert_accepted(result[0], acceptance['k_sat'])


def test_calc_ptf_ferrerjulia2004_general_texture_organic_matter_out():
    inputs, acceptance, out = prepare_vector_case(
        CASES_CALC_PTF_FERRERJULIA2004_GENERAL_TEXTURE_ORGANIC_MATTER
    )
    result = calc_ptf_ferrerjulia2004_general_texture_organic_matter(**inputs, out=out)
    assert result is out
    assert_accepted(result[0], acceptance['k_sat'])
