# @generated by ptfkit-codegen; DO NOT EDIT.

import importlib
import math
import sys
from unittest.mock import patch

import pytest

from ptfkit.usda_texture import (
    USDATextureClass,
    USDATextureFractions,
    estimate_usda_texture_fractions,
)


EXPECTED = {
    'sand': USDATextureFractions(90.0, 5.0, 5.0),
    'loamy sand': USDATextureFractions(79.0, 14.0, 7.0),
    'sandy loam': USDATextureFractions(65.0, 25.0, 10.0),
    'loam': USDATextureFractions(41.0, 42.0, 17.0),
    'silt loam': USDATextureFractions(22.0, 65.0, 13.0),
    'silt': USDATextureFractions(7.0, 87.0, 6.0),
    'sandy clay loam': USDATextureFractions(61.0, 12.0, 27.0),
    'clay loam': USDATextureFractions(33.0, 34.0, 33.0),
    'silty clay loam': USDATextureFractions(11.0, 56.0, 33.0),
    'sandy clay': USDATextureFractions(50.0, 5.0, 45.0),
    'silty clay': USDATextureFractions(5.0, 45.0, 50.0),
    'clay': USDATextureFractions(17.0, 13.0, 70.0),
}

SUM_TOLERANCE = 0.000000000001


def test_canonical_classes_and_authoritative_values() -> None:
    assert [member.value for member in USDATextureClass] == list(EXPECTED)
    assert {member.value for member in USDATextureClass} == set(EXPECTED)
    for name, expected in EXPECTED.items():
        actual = estimate_usda_texture_fractions(name)
        assert actual == expected
        assert all(math.isfinite(value) for value in actual)
        assert all(0.0 <= value <= 100.0 for value in actual)
        assert abs(sum(actual) - 100.0) <= SUM_TOLERANCE


def test_loam_has_the_official_representative_triplet() -> None:
    assert estimate_usda_texture_fractions('loam') == USDATextureFractions(41.0, 42.0, 17.0)


def test_enum_and_normalized_string_inputs() -> None:
    expected = USDATextureFractions(61.0, 12.0, 27.0)
    assert estimate_usda_texture_fractions(USDATextureClass.SANDY_CLAY_LOAM) == expected
    for value in ('Sandy Clay Loam', '  sandy   clay loam  ', 'sandy-clay-loam', 'sandy_clay_loam'):
        assert estimate_usda_texture_fractions(value) == expected


@pytest.mark.parametrize(
    'value',
    [
        'unknown',
        'fine sandy loam',
        'very fine sandy loam',
        'gravelly loam',
        'very gravelly clay',
        'L',
        'SL',
        'SCL',
        'loa',
    ],
)
def test_invalid_subclasses_modifiers_abbreviations_and_fuzzy_values(value: str) -> None:
    with pytest.raises(ValueError, match='Unknown USDA texture class') as error:
        estimate_usda_texture_fractions(value)
    message = str(error.value)
    assert repr(value) in message
    assert all(name in message for name in EXPECTED)


def test_module_import_reads_no_external_files_or_network() -> None:
    sys.modules.pop('ptfkit.usda_texture', None)
    with (
        patch('builtins.open', side_effect=AssertionError('unexpected file read')),
        patch('socket.socket', side_effect=AssertionError('unexpected network access')),
    ):
        importlib.import_module('ptfkit.usda_texture')
