# @generated by ptfkit-codegen; DO NOT EDIT.
from __future__ import annotations

import pytest

from _helpers import assert_close, prepare_vector_case
from ptfkit.lal1979 import (
    calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay,
    calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon,
    calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand,
    calc_ptf_lal1979_group_i_moisture_equivalent_from_clay,
    calc_ptf_lal1979_group_i_moisture_equivalent_from_sand,
    calc_ptf_lal1979_group_i_plasticity_index_from_clay,
    calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon,
    calc_ptf_lal1979_group_i_plasticity_index_from_sand,
    calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay,
    calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon,
    calc_ptf_lal1979_group_i_water_0bar_from_clay,
    calc_ptf_lal1979_group_i_water_0bar_from_sand,
    calc_ptf_lal1979_group_i_water_01bar_from_clay,
    calc_ptf_lal1979_group_i_water_01bar_from_sand,
    calc_ptf_lal1979_group_i_water_03bar_from_clay,
    calc_ptf_lal1979_group_i_water_03bar_from_sand,
    calc_ptf_lal1979_group_i_water_15bar_from_clay,
    calc_ptf_lal1979_group_i_water_15bar_from_sand,
    calc_ptf_lal1979_group_i_water_15bar_from_silt,
    calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay,
    calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand,
    calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt,
    calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay,
    calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand,
    calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt,
    calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon,
    calc_ptf_lal1979_group_ii_plasticity_index_from_silt,
    calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay,
    calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon,
    calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand,
    calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt,
    calc_ptf_lal1979_group_ii_water_0bar_from_clay,
    calc_ptf_lal1979_group_ii_water_0bar_from_sand,
    calc_ptf_lal1979_group_ii_water_01bar_from_clay,
    calc_ptf_lal1979_group_ii_water_01bar_from_sand,
    calc_ptf_lal1979_group_ii_water_03bar_from_clay,
    calc_ptf_lal1979_group_ii_water_03bar_from_sand,
    calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar,
    calc_ptf_lal1979_group_ii_water_15bar_from_clay,
    calc_ptf_lal1979_group_ii_water_15bar_from_sand,
    calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar,
)


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY = [
    ({'clay': 19.0}, {'water_0bar': 0.365}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_water_0bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_0bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_0bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_0bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_0bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_CLAY)
    result = calc_ptf_lal1979_group_i_water_0bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND = [
    ({'sand': 66.0}, {'water_0bar': 0.381}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_water_0bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_0bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_0bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_0bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_0bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(CASES_CALC_PTF_LAL1979_GROUP_I_WATER_0BAR_FROM_SAND)
    result = calc_ptf_lal1979_group_i_water_0bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY = [
    ({'clay': 38.0}, {'water_0bar': 0.448}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_0bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_0bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_0bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_0bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_0bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_0bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND = [
    ({'sand': 57.0}, {'water_0bar': 0.417}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_0bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_0bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_0bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_0bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_0bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_0BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_0bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_0bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY = [
    ({'clay': 19.0}, {'water_01bar': 0.159}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_water_01bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_01bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_01bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_01bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_01bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_01bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY = [
    ({'clay': 19.0}, {'water_03bar': 0.141}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_water_03bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_03bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_03bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_03bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_03bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_03bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND = [
    ({'sand': 66.0}, {'water_01bar': 0.166}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_water_01bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_01bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_01bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_01bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_01bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_01BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_01bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND = [
    ({'sand': 66.0}, {'water_03bar': 0.136}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_water_03bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_03bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_03bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_03bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_03bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_03BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_03bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY = [
    ({'clay': 38.0}, {'water_01bar': 0.194}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_01bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_01bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_01bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_01bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_01bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_01bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY = [
    ({'clay': 38.0}, {'water_03bar': 0.161}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_03bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_03bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND = [
    ({'sand': 57.0}, {'water_01bar': 0.2065}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_01bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_01bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_01bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_01bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_01bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_01BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_01bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_01bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND = [
    ({'sand': 57.0}, {'water_03bar': 0.178}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_03bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_03bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY = [
    ({'clay': 19.0}, {'water_15bar': 0.063}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_water_15bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_15bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND = [
    ({'sand': 66.0}, {'water_15bar': 0.049}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_water_15bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_15bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT = [
    ({'silt': 15.0}, {'water_15bar': 0.128}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT_IDS,
)
def test_calc_ptf_lal1979_group_i_water_15bar_from_silt_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_water_15bar_from_silt(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_silt_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_silt(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_water_15bar_from_silt_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_WATER_15BAR_FROM_SILT
    )
    result = calc_ptf_lal1979_group_i_water_15bar_from_silt(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY = [
    ({'clay': 38.0}, {'water_15bar': 0.1086}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_15bar_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_15bar_from_clay(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND = [
    ({'sand': 57.0}, {'water_15bar': 0.1472}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_15bar_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_15bar_from_sand(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY = [
    ({'clay': 19.0}, {'moisture_equivalent': 0.128}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_clay(**inputs)

    assert_close(
        result,
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND = [
    ({'sand': 66.0}, {'moisture_equivalent': 0.141}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_sand(**inputs)

    assert_close(
        result,
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_moisture_equivalent_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_MOISTURE_EQUIVALENT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_moisture_equivalent_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY = [
    ({'clay': 38.0}, {'moisture_equivalent': 0.152}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay(**inputs)

    assert_close(
        result,
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND = [
    ({'sand': 57.0}, {'moisture_equivalent': 0.17}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand(**inputs)

    assert_close(
        result,
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT = [
    ({'silt': 5.0}, {'moisture_equivalent': 0.15}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT_IDS,
)
def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt(**inputs)

    assert_close(
        result,
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt(**inputs, out=None)
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_MOISTURE_EQUIVALENT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_moisture_equivalent_from_silt(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['moisture_equivalent'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR = [
    ({'water_01bar': 0.17}, {'water_03bar': 0.1322}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar(**inputs)

    assert_close(
        result,
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_03BAR_FROM_WATER_01BAR
    )
    result = calc_ptf_lal1979_group_ii_water_03bar_from_water_01bar(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_03bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR = [
    ({'water_01bar': 0.17}, {'water_15bar': 0.0868}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR_IDS,
)
def test_calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar(**inputs)

    assert_close(
        result,
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar(**inputs, out=None)
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_WATER_15BAR_FROM_WATER_01BAR
    )
    result = calc_ptf_lal1979_group_ii_water_15bar_from_water_01bar(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['water_15bar'],
        absolute=0.001,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_fraction',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON = [
    ({'organic_carbon': 1.5}, {'upper_plastic_limit': 23.63}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS,
)
def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_organic_carbon(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON = [
    ({'organic_carbon': 1.5}, {'lower_plastic_limit': 18.37}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS,
)
def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_organic_carbon(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON = [
    ({'organic_carbon': 1.5}, {'plasticity_index': 5.56}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON_IDS,
)
def test_calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon(**inputs)

    assert_close(
        result,
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon(**inputs, out=None)
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_organic_carbon(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY = [
    ({'clay': 19.0}, {'upper_plastic_limit': 20.22}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_UPPER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_upper_plastic_limit_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY = [
    ({'clay': 19.0}, {'lower_plastic_limit': 15.96}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY = [
    ({'clay': 19.0}, {'plasticity_index': 4.57}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_i_plasticity_index_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_plasticity_index_from_clay(**inputs)

    assert_close(
        result,
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND = [
    ({'sand': 66.0}, {'lower_plastic_limit': 15.7}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_LOWER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_lower_plastic_limit_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND = [
    ({'sand': 66.0}, {'plasticity_index': 4.4}),
]
CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_i_plasticity_index_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_i_plasticity_index_from_sand(**inputs)

    assert_close(
        result,
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_i_plasticity_index_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_I_PLASTICITY_INDEX_FROM_SAND
    )
    result = calc_ptf_lal1979_group_i_plasticity_index_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON = [
    ({'organic_carbon': 0.42}, {'upper_plastic_limit': 30.9358}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON_IDS,
)
def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_organic_carbon(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON = [
    ({'organic_carbon': 0.42}, {'plasticity_index': 11.3476}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON_IDS,
)
def test_calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon(**inputs)

    assert_close(
        result,
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon(**inputs, out=None)
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_ORGANIC_CARBON
    )
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_organic_carbon(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY = [
    ({'clay': 38.0}, {'upper_plastic_limit': 30.67}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY = [
    ({'clay': 38.0}, {'lower_plastic_limit': 19.96}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY_IDS,
)
def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_CLAY
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_clay(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND = [
    ({'sand': 57.0}, {'upper_plastic_limit': 30.72}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND = [
    ({'sand': 57.0}, {'lower_plastic_limit': 20.19}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND_IDS,
)
def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SAND
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_sand(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT = [
    ({'silt': 5.0}, {'upper_plastic_limit': 29.99}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT_IDS,
)
def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt(**inputs)

    assert_close(
        result,
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt(**inputs, out=None)
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_UPPER_PLASTIC_LIMIT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_upper_plastic_limit_from_silt(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['upper_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT = [
    ({'silt': 5.0}, {'lower_plastic_limit': 19.51}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT_IDS,
)
def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt(**inputs)

    assert_close(
        result,
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt(**inputs, out=None)
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_LOWER_PLASTIC_LIMIT_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_lower_plastic_limit_from_silt(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['lower_plastic_limit'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT = [
    ({'silt': 5.0}, {'plasticity_index': 10.48}),
]
CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT_IDS = [
    'published_predictor_mean',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT,
    ids=CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT_IDS,
)
def test_calc_ptf_lal1979_group_ii_plasticity_index_from_silt_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_silt(**inputs)

    assert_close(
        result,
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_plasticity_index_from_silt_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_silt(**inputs, out=None)
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )


def test_calc_ptf_lal1979_group_ii_plasticity_index_from_silt_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_LAL1979_GROUP_II_PLASTICITY_INDEX_FROM_SILT
    )
    result = calc_ptf_lal1979_group_ii_plasticity_index_from_silt(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['plasticity_index'],
        absolute=0.1,
        relative=0.0,
        quantity='gravimetric_water_content',
        unit='mass_percent',
        source='registry',
    )
