# @generated by ptfkit-codegen; DO NOT EDIT.
from __future__ import annotations

import pytest

from _helpers import assert_close, prepare_vector_case
from ptfkit.vereecken1989 import (
    Vereecken1989DetailedPTFResult,
    Vereecken1989PTFResult,
    calc_ptf_vereecken1989,
    calc_ptf_vereecken1989_detailed,
)


CASES_CALC_PTF_VEREECKEN1989 = [
    (
        {'bulk_density': 1.466, 'carbon': 1.03, 'clay': 10.93, 'sand': 52.14},
        {
            'theta_r': 0.08406999999999999,
            'theta_s': 0.4060520000000001,
            'alpha': 0.003581613076579849,
            'n': 0.8602234826041976,
        },
    ),
]


@pytest.mark.parametrize(('inputs', 'expected'), CASES_CALC_PTF_VEREECKEN1989)
def test_calc_ptf_vereecken1989_verification(inputs: dict[str, float], expected: dict[str, float]):
    result = calc_ptf_vereecken1989(**inputs)

    assert_close(
        result.theta_r,
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s,
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha,
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n,
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )


def test_calc_ptf_vereecken1989_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_VEREECKEN1989, Vereecken1989PTFResult
    )
    result = calc_ptf_vereecken1989(**inputs, out=None)
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )


def test_calc_ptf_vereecken1989_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_VEREECKEN1989, Vereecken1989PTFResult
    )
    result = calc_ptf_vereecken1989(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )


CASES_CALC_PTF_VEREECKEN1989_DETAILED = [
    (
        {
            'bulk_density': 1.466,
            'carbon': 1.03,
            'clay': 10.93,
            'geometric_mean_particle_size': 0.07,
            'geometric_standard_deviation': 4.07,
            'particle_1000_500': 0.88,
            'particle_100_50': 16.3,
            'particle_10_2': 5.15,
            'particle_2000_1000': 0.25,
            'particle_200_100': 21.15,
            'particle_20_10': 7.0,
            'particle_500_200': 13.53,
            'particle_50_20': 24.83,
        },
        {
            'theta_r': 0.08277820000000001,
            'theta_s': 0.4060520000000001,
            'alpha': 0.02522115884641546,
            'n': 0.517175605329397,
        },
    ),
]


@pytest.mark.parametrize(('inputs', 'expected'), CASES_CALC_PTF_VEREECKEN1989_DETAILED)
def test_calc_ptf_vereecken1989_detailed_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_vereecken1989_detailed(**inputs)

    assert_close(
        result.theta_r,
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s,
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha,
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n,
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )


def test_calc_ptf_vereecken1989_detailed_array():
    inputs, expected, _out = prepare_vector_case(
        CASES_CALC_PTF_VEREECKEN1989_DETAILED, Vereecken1989DetailedPTFResult
    )
    result = calc_ptf_vereecken1989_detailed(**inputs, out=None)
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )


def test_calc_ptf_vereecken1989_detailed_out():
    inputs, expected, out = prepare_vector_case(
        CASES_CALC_PTF_VEREECKEN1989_DETAILED, Vereecken1989DetailedPTFResult
    )
    result = calc_ptf_vereecken1989_detailed(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='cm^3/cm^3',
        source='registry',
    )
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='cm^-1',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )
