# @generated by ptfkit-codegen; DO NOT EDIT.
from __future__ import annotations

import pytest

from _helpers import prepare_vector_case
from ptfkit.chakraborty2011 import (
    Chakraborty2011PTFResult,
    calc_ptf_chakraborty2011_eq1,
    calc_ptf_chakraborty2011_eq2,
    calc_ptf_chakraborty2011_eq3,
    calc_ptf_chakraborty2011_eq4,
    calc_ptf_chakraborty2011_eq5,
    calc_ptf_chakraborty2011_eq6,
)


CASES_CALC_PTF_CHAKRABORTY2011_EQ1 = [
    (
        {'clay': 20.0, 'silt': 30.0},
        {
            'water_content_100': 0.19758,
            'water_content_1500': 0.11702,
            'water_content_33': 0.2488,
            'water_content_500': 0.13528,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ1)
def test_calc_ptf_chakraborty2011_eq1_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq1(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq1_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ1, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq1(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq1_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ1, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq1(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


CASES_CALC_PTF_CHAKRABORTY2011_EQ2 = [
    (
        {'bulk_density': 1.5, 'sand': 50.0},
        {
            'water_content_100': 0.175765,
            'water_content_1500': 0.118315,
            'water_content_33': 0.219415,
            'water_content_500': 0.141025,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ2)
def test_calc_ptf_chakraborty2011_eq2_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq2(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq2_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ2, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq2(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq2_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ2, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq2(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


CASES_CALC_PTF_CHAKRABORTY2011_EQ3 = [
    (
        {'bulk_density': 1.5, 'clay': 20.0, 'silt': 30.0},
        {
            'water_content_100': 0.201085,
            'water_content_1500': 0.117865,
            'water_content_33': 0.25776,
            'water_content_500': 0.139175,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ3)
def test_calc_ptf_chakraborty2011_eq3_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq3(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq3_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ3, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq3(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq3_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ3, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq3(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


CASES_CALC_PTF_CHAKRABORTY2011_EQ4 = [
    (
        {'clay': 20.0, 'sand': 50.0, 'silt': 30.0},
        {
            'water_content_100': 0.19235,
            'water_content_1500': 0.11325,
            'water_content_33': 0.24397,
            'water_content_500': 0.13116,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ4)
def test_calc_ptf_chakraborty2011_eq4_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq4(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq4_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ4, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq4(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq4_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ4, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq4(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


CASES_CALC_PTF_CHAKRABORTY2011_EQ5 = [
    (
        {'bulk_density': 1.5, 'clay': 20.0, 'sand': 50.0, 'silt': 30.0},
        {
            'water_content_100': 0.19166,
            'water_content_1500': 0.110595,
            'water_content_33': 0.249785,
            'water_content_500': 0.131065,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ5)
def test_calc_ptf_chakraborty2011_eq5_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq5(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq5_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ5, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq5(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq5_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ5, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq5(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


CASES_CALC_PTF_CHAKRABORTY2011_EQ6 = [
    (
        {'bulk_density': 1.5, 'clay': 20.0, 'organic_carbon': 0.5, 'sand': 50.0, 'silt': 30.0},
        {
            'water_content_100': 0.19695,
            'water_content_1500': 0.113175,
            'water_content_33': 0.25207,
            'water_content_500': 0.13364,
        },
        1e-12,
        1e-12,
    ),
]


@pytest.mark.parametrize(('inputs', 'expected', 'rtol', 'atol'), CASES_CALC_PTF_CHAKRABORTY2011_EQ6)
def test_calc_ptf_chakraborty2011_eq6_golden(
    inputs: dict[str, float], expected: dict[str, float], rtol: float, atol: float
):
    result = calc_ptf_chakraborty2011_eq6(**inputs)

    assert result.water_content_33 == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100 == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500 == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500 == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq6_array():
    inputs, expected, rtol, atol, _out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ6, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq6(**inputs, out=None)
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )


def test_calc_ptf_chakraborty2011_eq6_out():
    inputs, expected, rtol, atol, out = prepare_vector_case(
        CASES_CALC_PTF_CHAKRABORTY2011_EQ6, Chakraborty2011PTFResult
    )
    result = calc_ptf_chakraborty2011_eq6(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert result.water_content_33[0] == pytest.approx(
        expected['water_content_33'], rel=rtol, abs=atol
    )
    assert result.water_content_100[0] == pytest.approx(
        expected['water_content_100'], rel=rtol, abs=atol
    )
    assert result.water_content_500[0] == pytest.approx(
        expected['water_content_500'], rel=rtol, abs=atol
    )
    assert result.water_content_1500[0] == pytest.approx(
        expected['water_content_1500'], rel=rtol, abs=atol
    )
