# @generated by ptfkit-codegen; DO NOT EDIT.
from __future__ import annotations

import pytest

from _helpers import assert_close, prepare_vector_case
from ptfkit.bai2022 import Bai2022PTFResult, calc_ptf_bai2022, calc_ptf_bai2022_bulk_density


CASES_CALC_PTF_BAI2022_BULK_DENSITY = [
    ({'clay': 17.2, 'sand': 18.13, 'slope': 0.9}, {'bulk_density': 1.13782}),
]
CASES_CALC_PTF_BAI2022_BULK_DENSITY_IDS = [
    'mean_texture_interior_slope',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'),
    CASES_CALC_PTF_BAI2022_BULK_DENSITY,
    ids=CASES_CALC_PTF_BAI2022_BULK_DENSITY_IDS,
)
def test_calc_ptf_bai2022_bulk_density_verification(
    inputs: dict[str, float], expected: dict[str, float]
):
    result = calc_ptf_bai2022_bulk_density(**inputs)

    assert_close(
        result,
        expected['bulk_density'],
        absolute=0.001,
        relative=0.0,
        quantity='dry_bulk_density',
        unit='gram_per_cubic_centimeter',
        source='registry',
    )


def test_calc_ptf_bai2022_bulk_density_array():
    inputs, expected, _out = prepare_vector_case(CASES_CALC_PTF_BAI2022_BULK_DENSITY)
    result = calc_ptf_bai2022_bulk_density(**inputs, out=None)
    assert_close(
        result[0],
        expected['bulk_density'],
        absolute=0.001,
        relative=0.0,
        quantity='dry_bulk_density',
        unit='gram_per_cubic_centimeter',
        source='registry',
    )


def test_calc_ptf_bai2022_bulk_density_out():
    inputs, expected, out = prepare_vector_case(CASES_CALC_PTF_BAI2022_BULK_DENSITY)
    result = calc_ptf_bai2022_bulk_density(**inputs, out=out)
    assert result is out
    assert_close(
        result[0],
        expected['bulk_density'],
        absolute=0.001,
        relative=0.0,
        quantity='dry_bulk_density',
        unit='gram_per_cubic_centimeter',
        source='registry',
    )


CASES_CALC_PTF_BAI2022 = [
    (
        {
            'altitude': 1000.0,
            'clay': 17.2,
            'depth': 100.0,
            'precipitation': 500.0,
            'sand': 18.13,
            'silt': 64.67,
            'slope': 0.9,
        },
        {
            'alpha': 0.011921759728631647,
            'n': 1.7433930000000002,
            'theta_r': 0.09204291885824034,
            'theta_s': 0.4984116325806734,
            'k_sat': 0.02655529995752791,
        },
    ),
]
CASES_CALC_PTF_BAI2022_IDS = [
    'mean_texture_positive_transforms',
]


@pytest.mark.parametrize(
    ('inputs', 'expected'), CASES_CALC_PTF_BAI2022, ids=CASES_CALC_PTF_BAI2022_IDS
)
def test_calc_ptf_bai2022_verification(inputs: dict[str, float], expected: dict[str, float]):
    result = calc_ptf_bai2022(**inputs)

    assert_close(
        result.alpha,
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='inverse_centimeter',
        source='registry',
    )
    assert_close(
        result.n,
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )
    assert_close(
        result.theta_r,
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.theta_s,
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.k_sat,
        expected['k_sat'],
        absolute=1e-5,
        relative=0.01,
        quantity='saturated_hydraulic_conductivity',
        unit='centimeter_per_minute',
        source='registry',
    )


def test_calc_ptf_bai2022_array():
    inputs, expected, _out = prepare_vector_case(CASES_CALC_PTF_BAI2022, Bai2022PTFResult)
    result = calc_ptf_bai2022(**inputs, out=None)
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='inverse_centimeter',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.k_sat[0],
        expected['k_sat'],
        absolute=1e-5,
        relative=0.01,
        quantity='saturated_hydraulic_conductivity',
        unit='centimeter_per_minute',
        source='registry',
    )


def test_calc_ptf_bai2022_out():
    inputs, expected, out = prepare_vector_case(CASES_CALC_PTF_BAI2022, Bai2022PTFResult)
    result = calc_ptf_bai2022(**inputs, out=out)
    for actual, expected_out in zip(result, out, strict=True):
        assert actual is expected_out
    assert_close(
        result.alpha[0],
        expected['alpha'],
        absolute=1e-5,
        relative=0.0,
        quantity='van_genuchten_alpha',
        unit='inverse_centimeter',
        source='registry',
    )
    assert_close(
        result.n[0],
        expected['n'],
        absolute=0.001,
        relative=0.0,
        quantity='van_genuchten_n',
        unit='dimensionless',
        source='registry',
    )
    assert_close(
        result.theta_r[0],
        expected['theta_r'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.theta_s[0],
        expected['theta_s'],
        absolute=0.001,
        relative=0.0,
        quantity='volumetric_water_content',
        unit='volume_fraction',
        source='registry',
    )
    assert_close(
        result.k_sat[0],
        expected['k_sat'],
        absolute=1e-5,
        relative=0.01,
        quantity='saturated_hydraulic_conductivity',
        unit='centimeter_per_minute',
        source='registry',
    )
