[package]
name = "ptfkit"
version = "0.3.0"
edition = "2024"
description = "Collection of published pedotransfer functions for estimating soil hydraulic properties"
license = "MIT"
readme = "README.md"
repository = "https://github.com/AgroDT/ptfkit"
documentation = "https://docs.rs/ptfkit"
keywords = ["pedotransfer", "soil", "hydrology", "hydraulics", "scientific"]
categories = ["science"]

[features]
default = ["inline"]
inline = []

[dev-dependencies]
assertables = "10.1.0"
