import re
import runpy
import sys
import tomllib
from pathlib import Path


expected = sys.argv[1].removeprefix('v')

with Path('targets/ptfkit-rs/Cargo.toml').open('rb') as file:
    rust = tomllib.load(file)['package']['version']

python = runpy.run_path('targets/ptfkit-py/src/ptfkit/_version.py')['__version__']

native_source = Path('targets/ptfkit-native/cmake/ptfkitVersion.cmake').read_text()
match = re.fullmatch(
    r'# @generated by ptfkit-codegen; do not edit\.\n'
    r'set\(PTFKIT_VERSION "([^"]+)"\)\n?',
    native_source,
)
if match is None:
    message = 'failed to read native version'
    raise SystemExit(message)
native = match.group(1)

versions = {'rust': rust, 'python': python, 'native': native}
mismatches = {name: version for name, version in versions.items() if version != expected}
if mismatches:
    details = ', '.join(f'{name}={version}' for name, version in mismatches.items())
    message = f'version mismatch for tag {expected}: {details}'
    raise SystemExit(message)
