repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix, lf]
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: generate
        name: regenerate targets
        language: system
        entry: cargo
        args: [run, --manifest-path, codegen/Cargo.toml, generate]
        files: '^(codegen/|specs/|targets/ptfkit-(rs|py)/src/)'
        pass_filenames: false
      - id: rustfmt-codegen
        name: rustfmt codegen
        language: system
        entry: cargo
        args: [fmt, --manifest-path, codegen/Cargo.toml, --all]
        files: '^codegen/.*\.rs$'
        pass_filenames: false
      - id: rustfmt-target
        name: rustfmt ptfkit-rs
        language: system
        entry: cargo
        args: [fmt, --manifest-path, targets/ptfkit-rs/Cargo.toml, --all]
        files: '^targets/ptfkit-rs/.*\.rs$'
        pass_filenames: false
      - id: clang-format
        name: clang-format
        language: system
        entry: clang-format
        args: [--style=file, -i]
        files: '\\.(c|h|cc|cpp|cppm|cxx|hpp)$'
      - id: uv-lock
        name: uv lock
        language: system
        entry: uv
        args: [--project, targets/ptfkit-py, lock, --check]
        files: .*(uv\.lock|pyproject\.toml|uv\.toml)$
        pass_filenames: false
      - id: uv-sync
        name: uv sync
        language: system
        entry: uv
        args: [--project, targets/ptfkit-py, sync, --frozen, --all-groups, --all-extras, --all-packages]
        always_run: true
        pass_filenames: false
      - id: ruff-check
        name: ruff check
        language: system
        entry: uv
        args: [--project, targets/ptfkit-py, run, --no-sync, ruff, check, --fix]
        types: [file, python]
      - id: ruff-format
        name: ruff format
        language: system
        entry: uv
        args: [--project, targets/ptfkit-py, run, --no-sync, ruff, format]
        types: [file, python]
      - id: ty-check
        name: ty check
        language: system
        entry: uv
        args: [--project, targets/ptfkit-py, run, --no-sync, ty, check]
        files: '^targets/ptfkit-py/.*\.py$'
