/* @generated by ptfkit-codegen; DO NOT EDIT. */

module;
#include <cstdint>
#include <limits>

export module ptfkit.adapters.usda_texture;

export namespace ptfkit::adapters {

enum class UsdaTexture : std::uint8_t {
    Sand = 0,
    LoamySand = 1,
    SandyLoam = 2,
    Loam = 3,
    SiltLoam = 4,
    Silt = 5,
    SandyClayLoam = 6,
    ClayLoam = 7,
    SiltyClayLoam = 8,
    SandyClay = 9,
    SiltyClay = 10,
    Clay = 11,
};

struct UsdaTextureFractions {
    double sand;
    double silt;
    double clay;
};

[[nodiscard]] constexpr UsdaTextureFractions fractions(UsdaTexture value) {
    switch (value) {
    case UsdaTexture::Sand:
        return {90, 5, 5};
    case UsdaTexture::LoamySand:
        return {79, 14, 7};
    case UsdaTexture::SandyLoam:
        return {65, 25, 10};
    case UsdaTexture::Loam:
        return {41, 42, 17};
    case UsdaTexture::SiltLoam:
        return {22, 65, 13};
    case UsdaTexture::Silt:
        return {7, 87, 6};
    case UsdaTexture::SandyClayLoam:
        return {61, 12, 27};
    case UsdaTexture::ClayLoam:
        return {33, 34, 33};
    case UsdaTexture::SiltyClayLoam:
        return {11, 56, 33};
    case UsdaTexture::SandyClay:
        return {50, 5, 45};
    case UsdaTexture::SiltyClay:
        return {5, 45, 50};
    case UsdaTexture::Clay:
        return {17, 13, 70};
    }
    const auto nan = std::numeric_limits<double>::quiet_NaN();
    return {nan, nan, nan};
}

} // namespace ptfkit::adapters
