# @generated by ptfkit-codegen; DO NOT EDIT.

# ruff: noqa: I001

r"""Bai et al. (2022), Loess Plateau PTFs for van Genuchten parameters and conductivity.

Reference:
    Bai, X., Shao, M. A., Jia, X., & Zhao, C. (2022). Prediction of the van Genuchten model soil
    hydraulic parameters for the 5-m soil profile in China's Loess Plateau. Catena, 210, 105889.
    [DOI: 10.1016/j.catena.2021.105889](https://doi.org/10.1016/j.catena.2021.105889)

Territory

:   A representative 370,000-square-kilometre loess area in China's Loess Plateau Region, spanning
    Shanxi, Henan, Shaanxi, Gansu, Ningxia, and Inner Mongolia.

Dataset

:   Dataset I used 84 samples from 7 profiles at 0-8 m for PTF development; Dataset II used 255
    samples from 85 profiles at 0-0.4 m for validation; Dataset III used 2,673 samples from 243
    profiles in 11 layers at 0-5 m for soil hydraulic parameter estimation.

"""

from __future__ import annotations

from typing import TYPE_CHECKING, Generic, NamedTuple, TypeVar, overload

from ptfkit._dispatch import call as _call
from ptfkit._ptfkit import (
    calc_ptf_bai2022_bulk_density as _calc_ptf_bai2022_bulk_density,
    calc_ptf_bai2022 as _calc_ptf_bai2022,
)


if TYPE_CHECKING:
    from numpy import floating
    from numpy.typing import ArrayLike, NDArray

T = TypeVar('T')


class Bai2022PTFResult(NamedTuple, Generic[T]):
    """Results returned by the matching PTF.

    Attributes:
        alpha: Inverse pressure-scale parameter of the van Genuchten model. (cm^-1)
        n: Pore-size distribution parameter of the van Genuchten model. (1)
        theta_r: Residual volumetric soil water content. (cm^3/cm^3)
        theta_s: Saturated volumetric soil water content. (cm^3/cm^3)
        k_sat: Saturated hydraulic conductivity. (cm/min)

    """

    alpha: T
    n: T
    theta_r: T
    theta_s: T
    k_sat: T


__all__ = ['Bai2022PTFResult', 'calc_ptf_bai2022', 'calc_ptf_bai2022_bulk_density']


@overload
def calc_ptf_bai2022_bulk_density(*, sand: float, slope: float, clay: float) -> floating: ...


@overload
def calc_ptf_bai2022_bulk_density(
    *,
    sand: ArrayLike,
    slope: ArrayLike,
    clay: ArrayLike,
    out: NDArray[floating] | None = None,
) -> NDArray[floating]: ...


def calc_ptf_bai2022_bulk_density(
    *,
    sand: float | ArrayLike,
    slope: float | ArrayLike,
    clay: float | ArrayLike,
    out: NDArray[floating] | None = None,
) -> floating | NDArray[floating]:
    """Estimate dry bulk density with Bai et al. Equation 7.

    Arguments:
        sand: Sand content determined by laser diffraction using USDA taxonomy. (%)
        slope: Cosine of the measured slope gradient; the source maps 0 degrees to 1 and 90 degrees
            to 0. (1)
        clay: Clay content determined by laser diffraction using USDA taxonomy. (%)
        out: Optional output arrays for in-place calculation.

    Returns:
        bulk_density: Dry bulk density predicted by Equation 7. (g/cm^3)

    Notes:
        Prediction target: Dry bulk density.
        The slope argument is the source-defined cosine-transformed slope gradient, not an angle in
            degrees.

    Warning:
        The observed marginal ranges describe the sampled soils and are not runtime clamps or
            evidence of applicability outside the study area.

    """
    return _call(
        _calc_ptf_bai2022_bulk_density,
        sand,
        slope,
        clay,
        out=out,
    )


@overload
def calc_ptf_bai2022(
    *,
    sand: float,
    silt: float,
    clay: float,
    depth: float,
    precipitation: float,
    slope: float,
    altitude: float,
) -> Bai2022PTFResult[floating]: ...


@overload
def calc_ptf_bai2022(
    *,
    sand: ArrayLike,
    silt: ArrayLike,
    clay: ArrayLike,
    depth: ArrayLike,
    precipitation: ArrayLike,
    slope: ArrayLike,
    altitude: ArrayLike,
    out: Bai2022PTFResult[NDArray[floating]] | None = None,
) -> Bai2022PTFResult[NDArray[floating]]: ...


def calc_ptf_bai2022(
    *,
    sand: float | ArrayLike,
    silt: float | ArrayLike,
    clay: float | ArrayLike,
    depth: float | ArrayLike,
    precipitation: float | ArrayLike,
    slope: float | ArrayLike,
    altitude: float | ArrayLike,
    out: Bai2022PTFResult[NDArray[floating]] | None = None,
) -> Bai2022PTFResult[floating] | Bai2022PTFResult[NDArray[floating]]:
    r"""Calculate the pedotransfer function.

    Estimate selected van Genuchten parameters and saturated hydraulic conductivity for Loess
    Plateau soils.

    Arguments:
        sand: Sand content determined by laser diffraction using USDA taxonomy. (%)
        silt: Silt content determined by laser diffraction using USDA taxonomy. (%)
        clay: Clay content determined by laser diffraction using USDA taxonomy. (%)
        depth: Continuous point depth in centimetres used by the selected depth-dependent equations.
            (cm)
        precipitation: Mean annual precipitation. (mm/year)
        slope: Cosine of the measured slope gradient; the source maps 0 degrees to 1 and 90 degrees
            to 0. The selected theta_r and Ks equations require a nonzero value because they contain
            logarithmic and reciprocal slope terms. (1)
        altitude: Altitude determined using a handheld portable GPS. (m)
        out: Optional output arrays for in-place calculation.

    Returns:
        Bai2022PTFResult: Results grouped by result attributes.

    Models:
        $h(\theta)$: van Genuchten model with m = 1 - 1 / n
        $k(h)$: Saturated hydraulic conductivity

    Notes:
        Prediction target: Residual and saturated volumetric water content, van Genuchten alpha and
            n, and saturated hydraulic conductivity.
        Table 4 selects the with-depth variants for alpha, n, theta_s, and Ks, and the without-depth
            variant for theta_r.
        EXP is the natural exponential. The equations use natural logarithms where Table 4 prints
            ln.
        This draft stages bulk density from Equation 7 before evaluating the theta_s and Ks
            equations, following the article's statement that bulk density was predicted and then
            used to estimate the hydraulic parameters.
        Depth is exposed as a continuous point coordinate in centimetres. When applying the PTF to a
            source-style interval-labelled layer, ptfkit uses the arithmetic midpoint of the
            interval.

    Warning:
        Midpoint encoding for interval-labelled layers is a reviewed ptfkit convention because the
            source does not publish its fitted layer-depth coordinate. It is not claimed as
            author-software parity.
        Inputs are not clamped. Values outside the documented domain, including zero or invalid
            logarithm and reciprocal arguments, follow ordinary IEEE 754 and NumPy-compatible
            floating-point behavior.
        This empirical regional model is calibrated for deep loess profiles in China's Loess Plateau
            and has no demonstrated global applicability.

    """
    values = _call(
        _calc_ptf_bai2022,
        sand,
        silt,
        clay,
        depth,
        precipitation,
        slope,
        altitude,
        out=out,
    )

    return Bai2022PTFResult(*values)
