/* @generated by ptfkit-codegen; DO NOT EDIT. */
#include <ptfkit/pidgeon1972.h>
#include "ufunc.h"

static const int calc_ptf_pidgeon1972_fc_types[] = {NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_fc_contiguous_loop(PyArrayMethod_Context *context,
                                                   char *const *data, const npy_intp *dimensions,
                                                   const npy_intp *strides,
                                                   NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_silt = (const double *)data[0];
    const double *in_clay = (const double *)data[1];
    const double *in_organic_matter = (const double *)data[2];
    double *out_field_capacity = (double *)data[3];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = in_silt[index];
        const double clay = in_clay[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_fc(silt, clay, organic_matter);
        out_field_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_fc_strided_loop(PyArrayMethod_Context *context, char *const *data,
                                                const npy_intp *dimensions, const npy_intp *strides,
                                                NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = *(const double *)(data[0] + index * strides[0]);
        const double clay = *(const double *)(data[1] + index * strides[1]);
        const double organic_matter = *(const double *)(data[2] + index * strides[2]);
        const double ptfkit_result = calc_ptf_pidgeon1972_fc(silt, clay, organic_matter);
        *(double *)(data[3] + index * strides[3]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_fc_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_fc_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_fc_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_fc_spec = {
    .name = "calc_ptf_pidgeon1972_fc",
    .nin = 3,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_fc_slots,
};

static const int calc_ptf_pidgeon1972_fc_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_fc_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                        char *const *data,
                                                        const npy_intp *dimensions,
                                                        const npy_intp *strides,
                                                        NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    double *out_field_capacity = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_fc_sand(sand);
        out_field_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_fc_sand_strided_loop(PyArrayMethod_Context *context,
                                                     char *const *data, const npy_intp *dimensions,
                                                     const npy_intp *strides,
                                                     NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_fc_sand(sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_fc_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_fc_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_fc_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_fc_sand_spec = {
    .name = "calc_ptf_pidgeon1972_fc_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_fc_sand_slots,
};

static const int calc_ptf_pidgeon1972_fc_sand_organic_matter_types[] = {NPY_DOUBLE, NPY_DOUBLE,
                                                                        NPY_DOUBLE};
static int calc_ptf_pidgeon1972_fc_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_field_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_fc_sand_organic_matter(sand, organic_matter);
        out_field_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_fc_sand_organic_matter_strided_loop(PyArrayMethod_Context *context,
                                                                    char *const *data,
                                                                    const npy_intp *dimensions,
                                                                    const npy_intp *strides,
                                                                    NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_fc_sand_organic_matter(sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_fc_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_fc_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_fc_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_fc_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_fc_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_fc_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_types[] = {NPY_DOUBLE, NPY_DOUBLE,
                                                                            NPY_DOUBLE};
static int calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_field_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_fc_vol_sand_organic_matter(sand, organic_matter);
        out_field_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_strided_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_fc_vol_sand_organic_matter(sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_fc_vol_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_pwp_types[] = {NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE,
                                                     NPY_DOUBLE};
static int calc_ptf_pidgeon1972_pwp_contiguous_loop(PyArrayMethod_Context *context,
                                                    char *const *data, const npy_intp *dimensions,
                                                    const npy_intp *strides,
                                                    NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_silt = (const double *)data[0];
    const double *in_clay = (const double *)data[1];
    const double *in_organic_matter = (const double *)data[2];
    double *out_permanent_wilting_point = (double *)data[3];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = in_silt[index];
        const double clay = in_clay[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_pwp(silt, clay, organic_matter);
        out_permanent_wilting_point[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_pwp_strided_loop(PyArrayMethod_Context *context, char *const *data,
                                                 const npy_intp *dimensions,
                                                 const npy_intp *strides,
                                                 NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = *(const double *)(data[0] + index * strides[0]);
        const double clay = *(const double *)(data[1] + index * strides[1]);
        const double organic_matter = *(const double *)(data[2] + index * strides[2]);
        const double ptfkit_result = calc_ptf_pidgeon1972_pwp(silt, clay, organic_matter);
        *(double *)(data[3] + index * strides[3]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_pwp_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_pwp_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_pwp_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_pwp_spec = {
    .name = "calc_ptf_pidgeon1972_pwp",
    .nin = 3,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_pwp_slots,
};

static const int calc_ptf_pidgeon1972_pwp_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_pwp_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                         char *const *data,
                                                         const npy_intp *dimensions,
                                                         const npy_intp *strides,
                                                         NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    double *out_permanent_wilting_point = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_pwp_sand(sand);
        out_permanent_wilting_point[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_pwp_sand_strided_loop(PyArrayMethod_Context *context,
                                                      char *const *data, const npy_intp *dimensions,
                                                      const npy_intp *strides,
                                                      NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_pwp_sand(sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_pwp_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_pwp_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_pwp_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_pwp_sand_spec = {
    .name = "calc_ptf_pidgeon1972_pwp_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_pwp_sand_slots,
};

static const int calc_ptf_pidgeon1972_pwp_sand_organic_matter_types[] = {NPY_DOUBLE, NPY_DOUBLE,
                                                                         NPY_DOUBLE};
static int calc_ptf_pidgeon1972_pwp_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_permanent_wilting_point = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_pwp_sand_organic_matter(sand, organic_matter);
        out_permanent_wilting_point[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_pwp_sand_organic_matter_strided_loop(PyArrayMethod_Context *context,
                                                                     char *const *data,
                                                                     const npy_intp *dimensions,
                                                                     const npy_intp *strides,
                                                                     NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_pwp_sand_organic_matter(sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_pwp_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_pwp_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_pwp_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_pwp_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_pwp_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_pwp_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_awc_types[] = {NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_awc_contiguous_loop(PyArrayMethod_Context *context,
                                                    char *const *data, const npy_intp *dimensions,
                                                    const npy_intp *strides,
                                                    NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_clay = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_available_water_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double clay = in_clay[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_awc(clay, organic_matter);
        out_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_awc_strided_loop(PyArrayMethod_Context *context, char *const *data,
                                                 const npy_intp *dimensions,
                                                 const npy_intp *strides,
                                                 NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double clay = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result = calc_ptf_pidgeon1972_awc(clay, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_awc_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_awc_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_awc_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_awc_spec = {
    .name = "calc_ptf_pidgeon1972_awc",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_awc_slots,
};

static const int calc_ptf_pidgeon1972_awc_sand_organic_matter_types[] = {NPY_DOUBLE, NPY_DOUBLE,
                                                                         NPY_DOUBLE};
static int calc_ptf_pidgeon1972_awc_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_available_water_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_awc_sand_organic_matter(sand, organic_matter);
        out_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_awc_sand_organic_matter_strided_loop(PyArrayMethod_Context *context,
                                                                     char *const *data,
                                                                     const npy_intp *dimensions,
                                                                     const npy_intp *strides,
                                                                     NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_awc_sand_organic_matter(sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_awc_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_awc_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_awc_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_awc_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_awc_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_awc_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_awc_coarse_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_awc_coarse_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                                char *const *data,
                                                                const npy_intp *dimensions,
                                                                const npy_intp *strides,
                                                                NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_coarse_sand = (const double *)data[0];
    double *out_available_water_capacity = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double coarse_sand = in_coarse_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_coarse_sand(coarse_sand);
        out_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_awc_coarse_sand_strided_loop(PyArrayMethod_Context *context,
                                                             char *const *data,
                                                             const npy_intp *dimensions,
                                                             const npy_intp *strides,
                                                             NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double coarse_sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_coarse_sand(coarse_sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_awc_coarse_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_awc_coarse_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_awc_coarse_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_awc_coarse_sand_spec = {
    .name = "calc_ptf_pidgeon1972_awc_coarse_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_awc_coarse_sand_slots,
};

static const int calc_ptf_pidgeon1972_awc_fine_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_awc_fine_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                              char *const *data,
                                                              const npy_intp *dimensions,
                                                              const npy_intp *strides,
                                                              NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_fine_sand = (const double *)data[0];
    double *out_available_water_capacity = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double fine_sand = in_fine_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_fine_sand(fine_sand);
        out_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_awc_fine_sand_strided_loop(PyArrayMethod_Context *context,
                                                           char *const *data,
                                                           const npy_intp *dimensions,
                                                           const npy_intp *strides,
                                                           NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double fine_sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_fine_sand(fine_sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_awc_fine_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_awc_fine_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_awc_fine_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_awc_fine_sand_spec = {
    .name = "calc_ptf_pidgeon1972_awc_fine_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_awc_fine_sand_slots,
};

static const int calc_ptf_pidgeon1972_awc_very_fine_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_awc_very_fine_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                                   char *const *data,
                                                                   const npy_intp *dimensions,
                                                                   const npy_intp *strides,
                                                                   NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_very_fine_sand = (const double *)data[0];
    double *out_available_water_capacity = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double very_fine_sand = in_very_fine_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_very_fine_sand(very_fine_sand);
        out_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_awc_very_fine_sand_strided_loop(PyArrayMethod_Context *context,
                                                                char *const *data,
                                                                const npy_intp *dimensions,
                                                                const npy_intp *strides,
                                                                NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double very_fine_sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_awc_very_fine_sand(very_fine_sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_awc_very_fine_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_awc_very_fine_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_awc_very_fine_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_awc_very_fine_sand_spec = {
    .name = "calc_ptf_pidgeon1972_awc_very_fine_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_awc_very_fine_sand_slots,
};

static const int calc_ptf_pidgeon1972_eawc_types[] = {NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE,
                                                      NPY_DOUBLE};
static int calc_ptf_pidgeon1972_eawc_contiguous_loop(PyArrayMethod_Context *context,
                                                     char *const *data, const npy_intp *dimensions,
                                                     const npy_intp *strides,
                                                     NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_silt = (const double *)data[0];
    const double *in_clay = (const double *)data[1];
    const double *in_organic_matter = (const double *)data[2];
    double *out_extended_available_water_capacity = (double *)data[3];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = in_silt[index];
        const double clay = in_clay[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_eawc(silt, clay, organic_matter);
        out_extended_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_eawc_strided_loop(PyArrayMethod_Context *context, char *const *data,
                                                  const npy_intp *dimensions,
                                                  const npy_intp *strides,
                                                  NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double silt = *(const double *)(data[0] + index * strides[0]);
        const double clay = *(const double *)(data[1] + index * strides[1]);
        const double organic_matter = *(const double *)(data[2] + index * strides[2]);
        const double ptfkit_result = calc_ptf_pidgeon1972_eawc(silt, clay, organic_matter);
        *(double *)(data[3] + index * strides[3]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_eawc_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_eawc_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_eawc_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_eawc_spec = {
    .name = "calc_ptf_pidgeon1972_eawc",
    .nin = 3,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_eawc_slots,
};

static const int calc_ptf_pidgeon1972_eawc_sand_types[] = {NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_eawc_sand_contiguous_loop(PyArrayMethod_Context *context,
                                                          char *const *data,
                                                          const npy_intp *dimensions,
                                                          const npy_intp *strides,
                                                          NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    double *out_extended_available_water_capacity = (double *)data[1];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double ptfkit_result = calc_ptf_pidgeon1972_eawc_sand(sand);
        out_extended_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_eawc_sand_strided_loop(PyArrayMethod_Context *context,
                                                       char *const *data,
                                                       const npy_intp *dimensions,
                                                       const npy_intp *strides,
                                                       NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double ptfkit_result = calc_ptf_pidgeon1972_eawc_sand(sand);
        *(double *)(data[1] + index * strides[1]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_eawc_sand_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_eawc_sand_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_eawc_sand_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_eawc_sand_spec = {
    .name = "calc_ptf_pidgeon1972_eawc_sand",
    .nin = 1,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_eawc_sand_slots,
};

static const int calc_ptf_pidgeon1972_eawc_sand_organic_matter_types[] = {NPY_DOUBLE, NPY_DOUBLE,
                                                                          NPY_DOUBLE};
static int calc_ptf_pidgeon1972_eawc_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_extended_available_water_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = in_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_sand_organic_matter(sand, organic_matter);
        out_extended_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_eawc_sand_organic_matter_strided_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_sand_organic_matter(sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_eawc_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_eawc_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_eawc_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_eawc_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_eawc_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_eawc_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_types[] = {
    NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_coarse_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_extended_available_water_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double coarse_sand = in_coarse_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter(coarse_sand, organic_matter);
        out_extended_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_strided_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double coarse_sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter(coarse_sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop,
     calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_slots,
};

static const int calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_types[] = {
    NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE};
static int calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_contiguous_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)strides;
    (void)transferdata;
    const double *in_fine_sand = (const double *)data[0];
    const double *in_organic_matter = (const double *)data[1];
    double *out_extended_available_water_capacity = (double *)data[2];
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double fine_sand = in_fine_sand[index];
        const double organic_matter = in_organic_matter[index];
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter(fine_sand, organic_matter);
        out_extended_available_water_capacity[index] = ptfkit_result;
    }
    return 0;
}

static int calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_strided_loop(
    PyArrayMethod_Context *context, char *const *data, const npy_intp *dimensions,
    const npy_intp *strides, NpyAuxData *transferdata) {
    (void)context;
    (void)transferdata;
    for (npy_intp index = 0; index < dimensions[0]; index++) {
        const double fine_sand = *(const double *)(data[0] + index * strides[0]);
        const double organic_matter = *(const double *)(data[1] + index * strides[1]);
        const double ptfkit_result =
            calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter(fine_sand, organic_matter);
        *(double *)(data[2] + index * strides[2]) = ptfkit_result;
    }
    return 0;
}
static PyType_Slot calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_slots[] = {
    {NPY_METH_strided_loop, calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_strided_loop},
    {NPY_METH_contiguous_loop, calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_contiguous_loop},
    {0, NULL},
};
static PyArrayMethod_Spec calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_spec = {
    .name = "calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter",
    .nin = 2,
    .nout = 1,
    .casting = NPY_SAME_KIND_CASTING,
    .slots = calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_slots,
};

int ptfkit_register_pidgeon1972(PyObject *module) {
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_fc", calc_ptf_pidgeon1972_fc_types, 3, 1,
                         &calc_ptf_pidgeon1972_fc_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_fc_sand", calc_ptf_pidgeon1972_fc_sand_types,
                         1, 1, &calc_ptf_pidgeon1972_fc_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_fc_sand_organic_matter",
                         calc_ptf_pidgeon1972_fc_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_fc_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_fc_vol_sand_organic_matter",
                         calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_fc_vol_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_pwp", calc_ptf_pidgeon1972_pwp_types, 3, 1,
                         &calc_ptf_pidgeon1972_pwp_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_pwp_sand",
                         calc_ptf_pidgeon1972_pwp_sand_types, 1, 1,
                         &calc_ptf_pidgeon1972_pwp_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_pwp_sand_organic_matter",
                         calc_ptf_pidgeon1972_pwp_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_pwp_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_awc", calc_ptf_pidgeon1972_awc_types, 2, 1,
                         &calc_ptf_pidgeon1972_awc_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_awc_sand_organic_matter",
                         calc_ptf_pidgeon1972_awc_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_awc_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_awc_coarse_sand",
                         calc_ptf_pidgeon1972_awc_coarse_sand_types, 1, 1,
                         &calc_ptf_pidgeon1972_awc_coarse_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_awc_fine_sand",
                         calc_ptf_pidgeon1972_awc_fine_sand_types, 1, 1,
                         &calc_ptf_pidgeon1972_awc_fine_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_awc_very_fine_sand",
                         calc_ptf_pidgeon1972_awc_very_fine_sand_types, 1, 1,
                         &calc_ptf_pidgeon1972_awc_very_fine_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_eawc", calc_ptf_pidgeon1972_eawc_types, 3, 1,
                         &calc_ptf_pidgeon1972_eawc_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_eawc_sand",
                         calc_ptf_pidgeon1972_eawc_sand_types, 1, 1,
                         &calc_ptf_pidgeon1972_eawc_sand_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_eawc_sand_organic_matter",
                         calc_ptf_pidgeon1972_eawc_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_eawc_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter",
                         calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_eawc_coarse_sand_organic_matter_spec) < 0)
        return -1;
    if (ptfkit_add_ufunc(module, "calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter",
                         calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_types, 2, 1,
                         &calc_ptf_pidgeon1972_eawc_fine_sand_organic_matter_spec) < 0)
        return -1;
    return 0;
}
