/* @generated by ptfkit-codegen; DO NOT EDIT. */
#include "ufunc.h"

static void calc_ptf_puckett1985_loop(char **args, const npy_intp *dimensions,
                                      const npy_intp *steps, void *data) {
    npy_intp index;
    for (index = 0; index < dimensions[0]; index++) {
        const double sand = *(const double *)args[0];
        const double fine_sand = *(const double *)args[1];
        const double clay = *(const double *)args[2];
        const double bulk_density = *(const double *)args[3];
        const double porosity = *(const double *)args[4];
        const double theta_0 = 0.264 * bulk_density + 1.60 * porosity - 0.706;
        const double theta_1 = 318.0 / 1000.0 * bulk_density + 1.69 * porosity - 0.834;
        const double theta_5 = 0.0001930 * fine_sand - 0.000357 * sand + 0.000182 * clay + 0.410;
        const double theta_10 = 0.0000712 * fine_sand - 0.000383 * sand + 0.000243 * clay + 0.415;
        const double theta_30 = 0.0000059 * fine_sand - 0.000348 * sand + 0.000321 * clay + 0.365;
        const double theta_60 = 0.0000003 * fine_sand - 0.000319 * sand + 0.000351 * clay + 0.330;
        const double theta_100 = 0.0000019 * fine_sand - 0.000302 * sand + 0.000362 * clay + 0.310;
        const double theta_500 = 0.0000140 * fine_sand - 0.000262 * sand + 0.000375 * clay + 0.265;
        const double theta_1000 = 0.0000197 * fine_sand - 0.000244 * sand + 0.000378 * clay + 0.264;
        const double theta_1500 = 0.0000254 * fine_sand - 0.000239 * sand + 0.000380 * clay + 0.239;
        const double k_sat = 4.36e-5 * exp(-0.1975 * clay);
        *(double *)args[5] = theta_0;
        *(double *)args[6] = theta_1;
        *(double *)args[7] = theta_5;
        *(double *)args[8] = theta_10;
        *(double *)args[9] = theta_30;
        *(double *)args[10] = theta_60;
        *(double *)args[11] = theta_100;
        *(double *)args[12] = theta_500;
        *(double *)args[13] = theta_1000;
        *(double *)args[14] = theta_1500;
        *(double *)args[15] = k_sat;
        for (int arg = 0; arg < 16; arg++)
            args[arg] += steps[arg];
    }
}
static PyUFuncGenericFunction calc_ptf_puckett1985_functions[] = {calc_ptf_puckett1985_loop};
static char calc_ptf_puckett1985_types[] = {
    NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE,
    NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE, NPY_DOUBLE};

int ptfkit_register_puckett1985(PyObject *module) {
    if (ptfkit_add_ufunc(module, "calc_ptf_puckett1985", calc_ptf_puckett1985_functions,
                         calc_ptf_puckett1985_types, 5, 11) < 0)
        return -1;
    return 0;
}
