[build-system]
requires = ["maturin>=1.8,<2"]
build-backend = "maturin"

[project]
name = "ptfkit"
version = "0.1.0"
description = "Pedotransfer functions for estimating soil hydraulic properties"
readme = "../../README.md"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering",
]
authors = [
    {name = "Dmitry Fomin", email = "fomin_ds@esoil.ru"},
    {name = "Petr Shumilin", email = "shumpet03@yandex.ru"},
    {name = "Kirill Tolstygin", email = "tolstygin_kd@esoil.ru"},
    {name = "Petr Tsymbarovich", email = "tpr@esoil.ru"},
]
maintainers = [
    {name = "Petr Tsymbarovich", email = "tpr@esoil.ru"},
    {name = "Kirill Tolstygin", email = "tolstygin_kd@esoil.ru"},
]
dependencies = [
    "cython>=3,<4",
    "numpy>=2.0,<3",
]

[project.urls]
Repository = "https://github.com/AgroDT/ptfkit"
Issues = "https://github.com/AgroDT/ptfkit/issues"
Documentation = "https://agrodt.github.io/ptfkit/"

[tool.maturin]
module-name = "ptfkit._rust"
python-source = "../../src"
