// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Clapp and Hornberger (1978) representative soil hydraulic parameters by texture.

# Reference

Clapp, R. B., & Hornberger, G. M. (1978). Empirical equations for some soil hydraulic
properties. Water Resources Research.

# Territory

United States

# Dataset

Desorption data reported by Holtan et al. (1968) for soils collected at 34 United States
localities; 1,446 soils remained from an initial set of more than 1,800 after the exclusions
described by the paper."]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum UsdaTextureClass {
    #[doc = r"USDA sand soil textural class."]
    Sand,
    #[doc = r"USDA loamy sand soil textural class."]
    LoamySand,
    #[doc = r"USDA sandy loam soil textural class."]
    SandyLoam,
    #[doc = r"USDA silt loam soil textural class."]
    SiltLoam,
    #[doc = r"USDA loam soil textural class."]
    Loam,
    #[doc = r"USDA sandy clay loam soil textural class."]
    SandyClayLoam,
    #[doc = r"USDA silty clay loam soil textural class."]
    SiltyClayLoam,
    #[doc = r"USDA clay loam soil textural class."]
    ClayLoam,
    #[doc = r"USDA sandy clay soil textural class."]
    SandyClay,
    #[doc = r"USDA silty clay soil textural class."]
    SiltyClay,
    #[doc = r"USDA clay soil textural class."]
    Clay,
}
impl From<UsdaTextureClass> for Clapp1978Parameters {
    fn from(value: UsdaTextureClass) -> Self {
        match value {
            UsdaTextureClass::Sand => Self {
                b: 4.05f64,
                saturation_suction: 3.5f64,
                wetting_front_suction: 4.66f64,
                saturated_water_content: 0.395f64,
                saturated_hydraulic_conductivity: 1.056f64,
                sorptivity: 1.52f64,
            },
            UsdaTextureClass::LoamySand => Self {
                b: 4.38f64,
                saturation_suction: 1.78f64,
                wetting_front_suction: 2.38f64,
                saturated_water_content: 0.41f64,
                saturated_hydraulic_conductivity: 0.938f64,
                sorptivity: 1.04f64,
            },
            UsdaTextureClass::SandyLoam => Self {
                b: 4.9f64,
                saturation_suction: 7.18f64,
                wetting_front_suction: 9.52f64,
                saturated_water_content: 0.435f64,
                saturated_hydraulic_conductivity: 0.208f64,
                sorptivity: 1.03f64,
            },
            UsdaTextureClass::SiltLoam => Self {
                b: 5.3f64,
                saturation_suction: 56.6f64,
                wetting_front_suction: 75.3f64,
                saturated_water_content: 0.485f64,
                saturated_hydraulic_conductivity: 0.0432f64,
                sorptivity: 1.26f64,
            },
            UsdaTextureClass::Loam => Self {
                b: 5.39f64,
                saturation_suction: 14.6f64,
                wetting_front_suction: 20.0f64,
                saturated_water_content: 0.451f64,
                saturated_hydraulic_conductivity: 0.0417f64,
                sorptivity: 0.693f64,
            },
            UsdaTextureClass::SandyClayLoam => Self {
                b: 7.12f64,
                saturation_suction: 8.63f64,
                wetting_front_suction: 11.7f64,
                saturated_water_content: 0.42f64,
                saturated_hydraulic_conductivity: 0.0378f64,
                sorptivity: 0.488f64,
            },
            UsdaTextureClass::SiltyClayLoam => Self {
                b: 7.75f64,
                saturation_suction: 14.6f64,
                wetting_front_suction: 19.7f64,
                saturated_water_content: 0.477f64,
                saturated_hydraulic_conductivity: 0.0102f64,
                sorptivity: 0.31f64,
            },
            UsdaTextureClass::ClayLoam => Self {
                b: 8.52f64,
                saturation_suction: 36.1f64,
                wetting_front_suction: 48.1f64,
                saturated_water_content: 0.476f64,
                saturated_hydraulic_conductivity: 0.0147f64,
                sorptivity: 0.537f64,
            },
            UsdaTextureClass::SandyClay => Self {
                b: 10.4f64,
                saturation_suction: 6.16f64,
                wetting_front_suction: 8.18f64,
                saturated_water_content: 0.426f64,
                saturated_hydraulic_conductivity: 0.013f64,
                sorptivity: 0.223f64,
            },
            UsdaTextureClass::SiltyClay => Self {
                b: 10.4f64,
                saturation_suction: 17.4f64,
                wetting_front_suction: 23.0f64,
                saturated_water_content: 0.492f64,
                saturated_hydraulic_conductivity: 0.0062f64,
                sorptivity: 0.242f64,
            },
            UsdaTextureClass::Clay => Self {
                b: 11.4f64,
                saturation_suction: 18.6f64,
                wetting_front_suction: 24.3f64,
                saturated_water_content: 0.482f64,
                saturated_hydraulic_conductivity: 0.0077f64,
                sorptivity: 0.268f64,
            },
        }
    }
}
#[cfg(test)]
fn is_close(actual: f64, expected: f64, published_tolerance: f64) -> bool {
    let tolerance = published_tolerance + 1e-12 + 1e-5 * expected.abs();
    (actual - expected).abs() <= tolerance
}
#[cfg(test)]
fn assert_close(actual: f64, expected: f64, published_tolerance: f64) {
    assert!(
        is_close(actual, expected, published_tolerance),
        "|{actual} - {expected}| exceeds the shared tolerance"
    );
}
#[cfg(test)]
mod comparator_tests {
    use super::*;
    #[test]
    fn accepts_below_and_rejects_above_tolerance() {
        let expected = 2.0;
        let tolerance = 1e-12 + 1e-5 * expected;
        assert!(is_close(expected + tolerance * 0.5, expected, 0.0));
        assert!(!is_close(expected + tolerance * 2.0, expected, 0.0));
    }
}
#[doc = r"Results returned by `calc_ptf_clapp1978`."]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Clapp1978Parameters {
    #[doc = r"Mean exponent of the moisture-characteristic power curve. (1)"]
    pub b: f64,
    #[doc = r"Representative saturation suction, calculated as the antilog of the mean logarithm of fitted
saturation-suction values. (cm)"]
    pub saturation_suction: f64,
    #[doc = r"Representative Green-Ampt wetting-front suction. (cm)"]
    pub wetting_front_suction: f64,
    #[doc = r"Mean saturated volumetric water content, taken as total porosity. (1)"]
    pub saturated_water_content: f64,
    #[doc = r"Mean saturated hydraulic conductivity reported by Li et al. (1976). (cm/min)"]
    pub saturated_hydraulic_conductivity: f64,
    #[doc = r"Representative sorptivity for the paper's single initial moisture deficit corresponding to
500-cm initial suction. (cm/min^(1/2))"]
    pub sorptivity: f64,
}
#[doc = r"Return representative soil hydraulic parameters for a USDA texture class.

# Arguments

  * soil_texture: USDA soil textural class used to select a row of Table 2.

# Returns

A [`Clapp1978Parameters`].

# Models

  * h(theta): Power-curve moisture characteristic with a parabolic gradual-air-entry section
    near saturation
  * k(h): Campbell relative-conductivity power relation

# Notes

Prediction target: Representative moisture-characteristic exponent, saturation suction,
wetting-front suction, saturated water content, saturated hydraulic conductivity, and sorptivity
for a soil textural class.
The representative wetting-front suctions use an inflection wetness of 0.92 to model gradual air
entry near saturation.
The sorptivity values use the average saturated hydraulic conductivities reported by Li et al.
(1976) and one initial moisture deficit at 500-cm suction.

# Warnings

The paper states that these unverified average values should not be used blindly because
saturation suction varies substantially within texture classes.
Sorptivity values must be treated cautiously because the conductivity averages may not represent
the same average soils as the other parameters."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_clapp1978(soil_texture: UsdaTextureClass) -> Clapp1978Parameters {
    soil_texture.into()
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn table_2_sand() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::Sand);
        assert_close(result.b, 4.05f64, 0f64);
        assert_close(result.saturation_suction, 3.5f64, 0f64);
        assert_close(result.wetting_front_suction, 4.66f64, 0f64);
        assert_close(result.saturated_water_content, 0.395f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 1.056f64, 0f64);
        assert_close(result.sorptivity, 1.52f64, 0f64);
    }
    #[test]
    fn table_2_loamy_sand() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::LoamySand);
        assert_close(result.b, 4.38f64, 0f64);
        assert_close(result.saturation_suction, 1.78f64, 0f64);
        assert_close(result.wetting_front_suction, 2.38f64, 0f64);
        assert_close(result.saturated_water_content, 0.41f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.938f64, 0f64);
        assert_close(result.sorptivity, 1.04f64, 0f64);
    }
    #[test]
    fn table_2_sandy_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SandyLoam);
        assert_close(result.b, 4.9f64, 0f64);
        assert_close(result.saturation_suction, 7.18f64, 0f64);
        assert_close(result.wetting_front_suction, 9.52f64, 0f64);
        assert_close(result.saturated_water_content, 0.435f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.208f64, 0f64);
        assert_close(result.sorptivity, 1.03f64, 0f64);
    }
    #[test]
    fn table_2_silt_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SiltLoam);
        assert_close(result.b, 5.3f64, 0f64);
        assert_close(result.saturation_suction, 56.6f64, 0f64);
        assert_close(result.wetting_front_suction, 75.3f64, 0f64);
        assert_close(result.saturated_water_content, 0.485f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0432f64, 0f64);
        assert_close(result.sorptivity, 1.26f64, 0f64);
    }
    #[test]
    fn table_2_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::Loam);
        assert_close(result.b, 5.39f64, 0f64);
        assert_close(result.saturation_suction, 14.6f64, 0f64);
        assert_close(result.wetting_front_suction, 20f64, 0f64);
        assert_close(result.saturated_water_content, 0.451f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0417f64, 0f64);
        assert_close(result.sorptivity, 0.693f64, 0f64);
    }
    #[test]
    fn table_2_sandy_clay_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SandyClayLoam);
        assert_close(result.b, 7.12f64, 0f64);
        assert_close(result.saturation_suction, 8.63f64, 0f64);
        assert_close(result.wetting_front_suction, 11.7f64, 0f64);
        assert_close(result.saturated_water_content, 0.42f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0378f64, 0f64);
        assert_close(result.sorptivity, 0.488f64, 0f64);
    }
    #[test]
    fn table_2_silty_clay_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SiltyClayLoam);
        assert_close(result.b, 7.75f64, 0f64);
        assert_close(result.saturation_suction, 14.6f64, 0f64);
        assert_close(result.wetting_front_suction, 19.7f64, 0f64);
        assert_close(result.saturated_water_content, 0.477f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0102f64, 0f64);
        assert_close(result.sorptivity, 0.31f64, 0f64);
    }
    #[test]
    fn table_2_clay_loam() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::ClayLoam);
        assert_close(result.b, 8.52f64, 0f64);
        assert_close(result.saturation_suction, 36.1f64, 0f64);
        assert_close(result.wetting_front_suction, 48.1f64, 0f64);
        assert_close(result.saturated_water_content, 0.476f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0147f64, 0f64);
        assert_close(result.sorptivity, 0.537f64, 0f64);
    }
    #[test]
    fn table_2_sandy_clay() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SandyClay);
        assert_close(result.b, 10.4f64, 0f64);
        assert_close(result.saturation_suction, 6.16f64, 0f64);
        assert_close(result.wetting_front_suction, 8.18f64, 0f64);
        assert_close(result.saturated_water_content, 0.426f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.013f64, 0f64);
        assert_close(result.sorptivity, 0.223f64, 0f64);
    }
    #[test]
    fn table_2_silty_clay() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::SiltyClay);
        assert_close(result.b, 10.4f64, 0f64);
        assert_close(result.saturation_suction, 17.4f64, 0f64);
        assert_close(result.wetting_front_suction, 23f64, 0f64);
        assert_close(result.saturated_water_content, 0.492f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0062f64, 0f64);
        assert_close(result.sorptivity, 0.242f64, 0f64);
    }
    #[test]
    fn table_2_clay() {
        let result = calc_ptf_clapp1978(UsdaTextureClass::Clay);
        assert_close(result.b, 11.4f64, 0f64);
        assert_close(result.saturation_suction, 18.6f64, 0f64);
        assert_close(result.wetting_front_suction, 24.3f64, 0f64);
        assert_close(result.saturated_water_content, 0.482f64, 0f64);
        assert_close(result.saturated_hydraulic_conductivity, 0.0077f64, 0f64);
        assert_close(result.sorptivity, 0.268f64, 0f64);
    }
}
