// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Cosby et al. (1984), United States.

# Reference

Cosby, B. J., Hornberger, G. M., Clapp, R. B., & Ginn, T. R. (1984). A statistical exploration
of the relationships of soil moisture characteristics to the physical properties of soils. Water
Resources Research, 20(6), 682-690.

# Territory

United States

# Dataset

1448 soil samples from Holtan et al. (1968) and Rawls et al. (1976)."]

#[doc = r"Results returned by `calc_ptf_cosby1984_univariate`."]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Cosby1984UnivariatePTFResult {
    #[doc = r"Mean slope of the moisture characteristic. (dimensionless)"]
    pub mean_b: f64,
    #[doc = r"Mean log saturation matric potential; the underlying potential is expressed in cm H2O. (reported
log value)"]
    pub mean_log_psi_s: f64,
    #[doc = r"Mean log saturated hydraulic conductivity; the underlying conductivity is expressed in inches
per hour. (reported log value)"]
    pub mean_log_k_sat: f64,
    #[doc = r"Mean saturated water content. (% volume/volume)"]
    pub mean_theta_s: f64,
    #[doc = r"Standard deviation of b. (dimensionless)"]
    pub sd_b: f64,
    #[doc = r"Standard deviation of log saturated hydraulic conductivity. (reported log value)"]
    pub sd_log_k_sat: f64,
    #[doc = r"Standard deviation of saturated water content. (% volume/volume)"]
    pub sd_theta_s: f64,
}
#[doc = r"Estimate Cosby et al. (1984) univariate hydraulic parameter statistics from soil texture.

# Arguments

  * sand: Sand content. (%)
  * silt: Silt content. (%)
  * clay: Clay content. (%)

# Returns

A [`Cosby1984UnivariatePTFResult`].

# Models

  * h(theta): Power function moisture characteristic
  * k(h): Saturated hydraulic conductivity parameter statistics

# Notes

Prediction target: Mean and standard deviation estimates for hydraulic parameters from sand,
silt, and clay percentages.
No back-transform is applied to logarithmic outputs.
Public API names are provisional for pilot testing.

# Warnings

Log-transformed output units use the pilot contract `reported log value`."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_cosby1984_univariate(
    sand: f64,
    silt: f64,
    clay: f64,
) -> Cosby1984UnivariatePTFResult {
    let mean_b = 2.91f64 + 0.159f64 * clay;
    let mean_log_psi_s = 1.88f64 - 0.0131f64 * sand;
    let mean_log_k_sat = -0.884f64 + 0.0153f64 * sand;
    let mean_theta_s = 48.9f64 - 0.126f64 * sand;
    let sd_b = 1.34f64 + 0.0500f64 * clay;
    let sd_log_k_sat = 0.459f64 + 0.00321f64 * silt;
    let sd_theta_s = 7.73f64 - 0.0730f64 * clay;
    Cosby1984UnivariatePTFResult {
        mean_b,
        mean_log_psi_s,
        mean_log_k_sat,
        mean_theta_s,
        sd_b,
        sd_log_k_sat,
        sd_theta_s,
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    fn assert_in_interval(actual: f64, lower: f64, upper: f64) {
        assert!(
            actual >= lower && actual <= upper,
            "actual {actual} is outside [{lower}, {upper}]"
        );
    }
    #[test]
    fn scalar_mid_texture() {
        let result = calc_ptf_cosby1984_univariate(50f64, 30f64, 20f64);
        assert_in_interval(result.mean_b, 6.089999999999993f64, 6.090000000000007f64);
        assert_in_interval(
            result.mean_log_psi_s,
            1.2249999999999983f64,
            1.2250000000000019f64,
        );
        assert_in_interval(
            result.mean_log_k_sat,
            -0.1190000000000001f64,
            -0.11899999999999988f64,
        );
        assert_in_interval(
            result.mean_theta_s,
            42.599999999999945f64,
            42.60000000000006f64,
        );
        assert_in_interval(result.sd_b, 2.3399999999999963f64, 2.3400000000000034f64);
        assert_in_interval(
            result.sd_log_k_sat,
            0.5552999999999991f64,
            0.5553000000000009f64,
        );
        assert_in_interval(
            result.sd_theta_s,
            6.2699999999999925f64,
            6.270000000000007f64,
        );
    }
    #[test]
    fn scalar_sandy_texture() {
        let result = calc_ptf_cosby1984_univariate(80f64, 15f64, 5f64);
        assert_in_interval(result.mean_b, 3.7049999999999965f64, 3.7050000000000036f64);
        assert_in_interval(
            result.mean_log_psi_s,
            0.8319999999999991f64,
            0.8320000000000008f64,
        );
        assert_in_interval(
            result.mean_log_k_sat,
            0.3399999999999996f64,
            0.34000000000000047f64,
        );
        assert_in_interval(
            result.mean_theta_s,
            38.81999999999994f64,
            38.82000000000006f64,
        );
        assert_in_interval(result.sd_b, 1.5899999999999983f64, 1.5900000000000019f64);
        assert_in_interval(
            result.sd_log_k_sat,
            0.5071499999999991f64,
            0.5071500000000009f64,
        );
        assert_in_interval(
            result.sd_theta_s,
            7.364999999999993f64,
            7.365000000000007f64,
        );
    }
}
