// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Point water-retention regressions for tropical Sri Lankan soils.

# Reference

Gunarathna, M. H. J. P., Sakai, K., Nakandakari, T., Momii, K., Kumari, M. K. N., & Amarasekara,
M. G. T. S. (2019). Pedotransfer functions to estimate hydraulic properties of tropical Sri
Lankan soils. Soil & Tillage Research, 190, 109-119. https://doi.org/10.1016/j.still.2019.02.009
DOI: 10.1016/j.still.2019.02.009 (https://doi.org/10.1016/j.still.2019.02.009)

# Territory

Tropical Sri Lanka.

# Dataset

323 soil horizons retained after removing samples with missing water-content data from the
SRI-CANSOL survey of 110 profiles. The survey covers almost all soil series and land uses except
the northern part of Sri Lanka. Models were evaluated using tenfold cross-validation."]

#[doc = r"Estimate volumetric water content at -10 kPa using Set 1.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)

# Returns

  * theta_10: Volumetric water content at -10 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -10 kPa.
Equation evidence: Table 3, VWC10, Set 1.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds.
Section 3.1 reports slight overprediction above 64% sand at this pressure."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc10_set1(sand: f64) -> f64 {
    0.4802f64 - 0.0037f64 * sand
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc10_set1_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc10_set1(65.1f64);
        assert_close(
            result,
            0.23933f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -10 kPa using Set 2.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)

# Returns

  * theta_10: Volumetric water content at -10 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -10 kPa.
Equation evidence: Table 3, VWC10, Set 2.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc10_set2(sand: f64, silt: f64) -> f64 {
    0.3967f64 - 0.0029f64 * sand + 0.0025f64 * silt
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc10_set2_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc10_set2(65.1f64, 13.1f64);
        assert_close(
            result,
            0.24066f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -10 kPa using Set 3.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)
  * bulk_density: Bulk density measured using undisturbed cores. (g/cm3)

# Returns

  * theta_10: Volumetric water content at -10 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -10 kPa.
Equation evidence: Table 3, VWC10, Set 3.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc10_set3(sand: f64, silt: f64, bulk_density: f64) -> f64 {
    0.4436f64 - 0.0028f64 * sand + 0.0024f64 * silt - 0.034f64 * bulk_density
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc10_set3_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc10_set3(65.1f64, 13.1f64, 1.49f64);
        assert_close(
            result,
            0.2421f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -10 kPa using Set 4.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)
  * organic_carbon: Organic carbon percentage measured by the Walkley-Black method. (%)

# Returns

  * theta_10: Volumetric water content at -10 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -10 kPa.
Equation evidence: Table 3, VWC10, Set 4.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc10_set4(sand: f64, silt: f64, organic_carbon: f64) -> f64 {
    0.3951f64 - 0.0029f64 * sand + 0.0023f64 * silt + 0.0052f64 * organic_carbon.powi(2)
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc10_set4_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc10_set4(65.1f64, 13.1f64, 0.6f64);
        assert_close(
            result,
            0.238312f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa using Set 1.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)

# Returns

  * theta_33: Volumetric water content at -33 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -33 kPa.
Equation evidence: Table 3, VWC33, Set 1.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds.
Section 3.1 reports slight overprediction above 66% sand at this pressure."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc33_set1(sand: f64) -> f64 {
    0.4357f64 - 0.0035f64 * sand
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc33_set1_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc33_set1(65.1f64);
        assert_close(
            result,
            0.20785f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa using Set 2.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)

# Returns

  * theta_33: Volumetric water content at -33 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -33 kPa.
Equation evidence: Table 3, VWC33, Set 2.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc33_set2(sand: f64, silt: f64) -> f64 {
    0.3701f64 - 0.0029f64 * sand + 0.0020f64 * silt
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc33_set2_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc33_set2(65.1f64, 13.1f64);
        assert_close(
            result,
            0.20751f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa using Set 3.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)
  * bulk_density: Bulk density measured using undisturbed cores. (g/cm3)

# Returns

  * theta_33: Volumetric water content at -33 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -33 kPa.
Equation evidence: Table 3, VWC33, Set 3.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc33_set3(sand: f64, silt: f64, bulk_density: f64) -> f64 {
    0.4236f64 - 0.0028f64 * sand + 0.0018f64 * silt - 0.0388f64 * bulk_density
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc33_set3_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc33_set3(65.1f64, 13.1f64, 1.49f64);
        assert_close(
            result,
            0.207088f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa using Set 4.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * silt: Silt percentage measured by the pipette method. (%)
  * organic_carbon: Organic carbon percentage measured by the Walkley-Black method. (%)

# Returns

  * theta_33: Volumetric water content at -33 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -33 kPa.
Equation evidence: Table 3, VWC33, Set 4.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc33_set4(sand: f64, silt: f64, organic_carbon: f64) -> f64 {
    0.3686f64 - 0.0029f64 * sand + 0.0018f64 * silt + 0.0046f64 * organic_carbon.powi(2)
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc33_set4_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc33_set4(65.1f64, 13.1f64, 0.6f64);
        assert_close(
            result,
            0.205046f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -1500 kPa using Set 1.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)

# Returns

  * theta_1500: Volumetric water content at -1500 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -1500 kPa.
Equation evidence: Table 3, VWC1500, Set 1.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds.
Section 3.1 reports slight overprediction above 66% sand at this pressure."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc1500_set1(sand: f64) -> f64 {
    0.3426f64 - 0.003f64 * sand
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc1500_set1_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc1500_set1(65.1f64);
        assert_close(
            result,
            0.1473f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -1500 kPa using Set 3.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * bulk_density: Bulk density measured using undisturbed cores. (g/cm3)

# Returns

  * theta_1500: Volumetric water content at -1500 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -1500 kPa.
Equation evidence: Table 3, VWC1500, Set 3.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc1500_set3(sand: f64, bulk_density: f64) -> f64 {
    0.6397f64 - 0.0028f64 * sand - 0.385f64 * bulk_density + 0.1169f64 * bulk_density.powi(2)
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc1500_set3_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc1500_set3(65.1f64, 1.49f64);
        assert_close(
            result,
            0.14329969f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -1500 kPa using Set 4.

# Arguments

  * sand: Sand percentage measured by sieve analysis. (%)
  * organic_carbon: Organic carbon percentage measured by the Walkley-Black method. (%)

# Returns

  * theta_1500: Volumetric water content at -1500 kPa matric potential. (mm/mm)

# Notes

Prediction target: Volumetric water content at -1500 kPa.
Equation evidence: Table 3, VWC1500, Set 4.
Input ranges describe the study observations, not enforced validity limits.

# Warnings

Predictions are empirical and are not clipped to physical bounds."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_gunarathna2019_vwc1500_set4(sand: f64, organic_carbon: f64) -> f64 {
    0.3278f64 - 0.0028f64 * sand + 0.0082f64 * organic_carbon.powi(2)
}
#[cfg(test)]
mod calc_ptf_gunarathna2019_vwc1500_set4_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn published_predictor_means() {
        let result = calc_ptf_gunarathna2019_vwc1500_set4(65.1f64, 0.6f64);
        assert_close(
            result,
            0.148472f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
