// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Jabro (1992), United States.

# Reference

Jabro, J. D. (1992). Estimation of saturated hydraulic conductivity of soils from particle size
distribution and bulk density data. Transactions of the ASAE, 35(2), 557-560.
DOI: 10.13031/2013.28633 (https://doi.org/10.13031/2013.28633)

# Territory

USA

# Dataset

Southern Cooperation Series Bulletins (Dan et al., 1983; Nofziger et al., 1983; Quisenberry et
al., 1987), 350 samples; validation on Duffield silt loam data."]

#[cfg(test)]
fn is_close(actual: f64, expected: f64, published_tolerance: f64) -> bool {
    let tolerance = published_tolerance + 1e-12 + 1e-5 * expected.abs();
    (actual - expected).abs() <= tolerance
}
#[cfg(test)]
fn assert_close(actual: f64, expected: f64, published_tolerance: f64) {
    assert!(
        is_close(actual, expected, published_tolerance),
        "|{actual} - {expected}| exceeds the shared tolerance"
    );
}
#[cfg(test)]
mod comparator_tests {
    use super::*;
    #[test]
    fn accepts_below_and_rejects_above_tolerance() {
        let expected = 2.0;
        let tolerance = 1e-12 + 1e-5 * expected;
        assert!(is_close(expected + tolerance * 0.5, expected, 0.0));
        assert!(!is_close(expected + tolerance * 2.0, expected, 0.0));
    }
}
#[doc = r"Estimate saturated hydraulic conductivity from silt, clay, and bulk density.

# Arguments

  * silt: Silt content, 0.002-0.05 mm. (%)
  * clay: Clay content, <0.002 mm. (%)
  * bulk_density: Bulk density. (g/cm^3)

# Returns

  * k_sat: Saturated hydraulic conductivity. (m/s)

# Models

  * k(h): Saturated hydraulic conductivity

# Notes

Prediction target: Saturated hydraulic conductivity from silt, clay, and bulk density.
Sand is not an input to the model.

# Warnings

The formula uses base-10 logarithms of silt and clay."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_jabro1992(silt: f64, clay: f64, bulk_density: f64) -> f64 {
    let log10_k_sat_cm_per_hour =
        9.56f64 - 0.81f64 * silt.log10() - 1.09f64 * clay.log10() - 4.64f64 * bulk_density;
    10.0f64.powf(log10_k_sat_cm_per_hour) * (0.01f64 / 3600.0f64)
}
#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn loamy_sand_min_bd() {
        let result = calc_ptf_jabro1992(10f64, 5f64, 1.26f64);
        assert_close(result, 0.0003849640675896946f64, 0f64);
    }
    #[test]
    fn loam() {
        let result = calc_ptf_jabro1992(38.72f64, 11.05f64, 1.42f64);
        assert_close(result, 0.000009804037952717678f64, 0f64);
    }
    #[test]
    fn silty_clay_loam_max_silt() {
        let result = calc_ptf_jabro1992(52f64, 30f64, 1.97f64);
        assert_close(result, 0.000000007292435947882127f64, 0f64);
    }
    #[test]
    fn sandy_clay_min_silt_max_clay() {
        let result = calc_ptf_jabro1992(0.2f64, 44f64, 1.61f64);
        assert_close(result, 0.00002032824027706267f64, 0f64);
    }
}
