// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Li et al. (2007), Fengqiu County, North China Plain, China.

# Reference

Li, Y., Chen, D., White, R. E., Zhu, A., & Zhang, J. (2007). Estimating soil hydraulic
properties of Fengqiu County soils in the North China Plain using pedo-transfer functions.
Geoderma, 138(3-4), 261-271.
DOI: 10.1016/j.geoderma.2006.11.018 (https://doi.org/10.1016/j.geoderma.2006.11.018)

# Territory

Fengqiu County soils in the North China Plain, China

# Dataset

63 soil water retention curves and 36 saturated soil hydraulic conductivity samples from seven
soil profiles."]

#[doc = r"Results returned by `calc_ptf_li2007`."]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Li2007PTFResult {
    #[doc = r"Saturated water content. (cm^3/cm^3)"]
    pub theta_s: f64,
    #[doc = r"Van Genuchten alpha parameter, inversely related to air-entry suction. (cm^-1)"]
    pub a_vg: f64,
    #[doc = r"Van Genuchten n parameter that characterizes pore-size distribution. (dimensionless)"]
    pub n_vg: f64,
    #[doc = r"Saturated hydraulic conductivity. (m/s)"]
    pub k_sat: f64,
}
#[doc = r"Estimate van Genuchten parameters and saturated hydraulic conductivity for Fengqiu County soils.

# Arguments

  * sand: Sand content, 0.02-2 mm. (%)
  * silt: Silt content, 0.02-0.002 mm. (%)
  * clay: Clay content, <0.002 mm. (%)
  * bulk_density: Bulk density. (g/cm^3)
  * soil_organic_matter: Soil organic matter. (%)

# Returns

A [`Li2007PTFResult`].

# Models

  * h(theta): Van Genuchten model without residual water content term
  * k(h): Saturated hydraulic conductivity

# Notes

Prediction target: Van Genuchten saturated water content, alpha, n, and saturated hydraulic
conductivity.

# Warnings

The formulas use natural logarithms of selected inputs."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_li2007(
    sand: f64,
    silt: f64,
    clay: f64,
    bulk_density: f64,
    soil_organic_matter: f64,
) -> Li2007PTFResult {
    let sand_ln = sand.ln();
    let silt_ln = silt.ln();
    let clay_ln = clay.ln();
    let soil_organic_matter_ln = soil_organic_matter.ln();
    let bulk_density_ln = bulk_density.ln();
    let theta_s = (-1.531f64 + 0.212f64 * sand_ln + 0.006f64 * silt
        - 0.051f64 * soil_organic_matter
        - 0.566f64 * bulk_density_ln)
        .exp();
    let a_vg = (-67.408f64 - 0.040f64 * silt - 0.670f64 * silt_ln - 2.189f64 * soil_organic_matter
        + 1.410f64 * soil_organic_matter_ln
        + 78.400f64 * bulk_density
        - 121.331f64 * bulk_density_ln)
        .exp();
    let n_vg = 1.488f64 + 0.002f64 * silt_ln + 0.013f64 * clay - 0.248f64 * clay_ln
        + 0.048f64 * soil_organic_matter_ln
        + 0.451f64 * bulk_density_ln;
    let k_sat_cm_per_day = (13.262f64
        - 1.914f64 * sand_ln
        - 0.974f64 * silt_ln
        - 0.058f64 * clay
        - 1.709f64 * soil_organic_matter_ln
        + 2.885f64 * soil_organic_matter
        - 8.026f64 * bulk_density_ln)
        .exp();
    let k_sat = k_sat_cm_per_day * (1.0f64 / 8640000.0f64);
    Li2007PTFResult {
        theta_s,
        a_vg,
        n_vg,
        k_sat,
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    fn assert_in_interval(actual: f64, lower: f64, upper: f64) {
        assert!(
            actual >= lower && actual <= upper,
            "actual {actual} is outside [{lower}, {upper}]"
        );
    }
    #[test]
    fn loamy_sand() {
        let result = calc_ptf_li2007(85f64, 10f64, 5f64, 1.2f64, 0.21f64);
        assert_in_interval(result.theta_s, 0.5256803583157428f64, 0.525680358315757f64);
        assert_in_interval(result.a_vg, 0.9491464758307003f64, 0.9491464758307145f64);
        assert_in_interval(result.n_vg, 1.1657804980996864f64, 1.1657804980997148f64);
        assert_in_interval(
            result.k_sat,
            0.000006549110367333487f64,
            0.000006549110367333595f64,
        );
    }
    #[test]
    fn loam() {
        let result = calc_ptf_li2007(50.23f64, 38.72f64, 11.05f64, 1.42f64, 0.65f64);
        assert_in_interval(result.theta_s, 0.4965952612769715f64, 0.4965952612769786f64);
        assert_in_interval(result.a_vg, 0.00951998984195053f64, 0.009519989841950752f64);
        assert_in_interval(result.n_vg, 1.1806286355148912f64, 1.1806286355149196f64);
        assert_in_interval(
            result.k_sat,
            0.00000045117324656201886f64,
            0.00000045117324656202564f64,
        );
    }
    #[test]
    fn silty_clay() {
        let result = calc_ptf_li2007(12.88f64, 60f64, 27.12f64, 1.48f64, 1.02f64);
        assert_in_interval(result.theta_s, 0.4053061510618573f64, 0.4053061510618644f64);
        assert_in_interval(
            result.a_vg,
            0.0018530400762371648f64,
            0.0018530400762371926f64,
        );
        assert_in_interval(result.n_vg, 1.208042873979729f64, 1.2080428739797575f64);
        assert_in_interval(
            result.k_sat,
            0.0000015151432632107082f64,
            0.0000015151432632107353f64,
        );
    }
}
