// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Rawls et al. (2003), organic-carbon effects on soil water retention.

# Reference

Rawls, W. J., Pachepsky, Y. A., Ritchie, J. C., Sobecki, T. M., & Bloodworth, H. (2003). Effect
of soil organic carbon on soil water retention. Geoderma, 116(1-2), 61-76.
DOI: 10.1016/S0016-7061(03)00094-6 (https://doi.org/10.1016/S0016-7061(03)00094-6)

# Territory

United States

# Dataset

Approximately 12,000 samples from the USDA National Soil Characterization database; equations
were evaluated with NRCS pilot-study data."]

#[inline]
fn theta_33_tree(texture: crate::definitions::soil::UsdaTextureClass, carbon: f64) -> f64 {
    match texture {
        crate::definitions::soil::UsdaTextureClass::Sand => {
            if carbon < 2.1f64 {
                0.108f64
            } else if carbon < 4.8f64 {
                0.28f64
            } else if carbon < 7.7f64 {
                0.35f64
            } else {
                0.394f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::LoamySand => {
            if carbon < 2.1f64 {
                0.151f64
            } else if carbon < 4.8f64 {
                0.28f64
            } else if carbon < 7.7f64 {
                0.35f64
            } else {
                0.394f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::SandyLoam => {
            if carbon < 1.1f64 {
                0.204f64
            } else if carbon < 2.1f64 {
                0.244f64
            } else if carbon < 4.8f64 {
                0.28f64
            } else if carbon < 7.7f64 {
                0.35f64
            } else {
                0.549f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::Loam
        | crate::definitions::soil::UsdaTextureClass::SandyClay => {
            if carbon < 1.7f64 {
                0.272f64
            } else if carbon < 4.2f64 {
                0.305f64
            } else if carbon < 8.5f64 {
                0.353f64
            } else {
                0.383f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::SandyClayLoam => {
            if carbon < 1.7f64 {
                0.272f64
            } else if carbon < 4.2f64 {
                0.305f64
            } else if carbon < 8.5f64 {
                0.393f64
            } else {
                0.464f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::SiltLoam
        | crate::definitions::soil::UsdaTextureClass::Silt => {
            if carbon < 1.5f64 {
                0.315f64
            } else if carbon < 4.2f64 {
                0.338f64
            } else if carbon < 8.5f64 {
                0.393f64
            } else {
                0.464f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::ClayLoam => {
            if carbon < 1.5f64 {
                0.315f64
            } else if carbon < 4.2f64 {
                0.338f64
            } else if carbon < 8.5f64 {
                0.353f64
            } else {
                0.464f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::SiltyClayLoam => {
            if carbon < 4.2f64 {
                0.361f64
            } else {
                0.548f64
            }
        }
        crate::definitions::soil::UsdaTextureClass::SiltyClay => 0.397f64,
        crate::definitions::soil::UsdaTextureClass::Clay => 0.426f64,
    }
}
#[inline]
fn theta_1500_tree(clay: f64, sand: f64, carbon: f64) -> f64 {
    if clay < 26.0f64 {
        if clay < 14.0f64 {
            if carbon < 2.3f64 {
                if clay < 8.0f64 {
                    if sand < 80.0f64 {
                        if carbon < 1.5f64 { 0.061f64 } else { 0.085f64 }
                    } else {
                        0.04f64
                    }
                } else if clay < 12.0f64 {
                    0.082f64
                } else {
                    0.1f64
                }
            } else if carbon < 6.5f64 {
                0.11f64
            } else {
                0.159f64
            }
        } else if clay < 19.0f64 {
            if carbon < 5.8f64 {
                if clay < 17.0f64 { 0.116f64 } else { 0.128f64 }
            } else {
                0.167f64
            }
        } else if clay < 23.0f64 {
            0.143f64
        } else {
            0.16f64
        }
    } else if clay < 44.0f64 {
        if clay < 33.0f64 {
            if clay < 29.0f64 { 0.173f64 } else { 0.193f64 }
        } else if clay < 37.4f64 {
            0.211f64
        } else {
            0.229f64
        }
    } else if clay < 54.0f64 {
        if clay < 48.0f64 { 0.253f64 } else { 0.275f64 }
    } else if clay < 67.0f64 {
        0.296f64
    } else {
        0.323f64
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa with the published regression tree.

# Arguments

  * soil_texture: USDA soil textural class used to traverse Figure 2.
  * soil_organic_carbon: Soil organic carbon content by mass. (% mass)

# Returns

  * theta_33: Volumetric soil water content at -33 kPa. (cm³/cm³)

# Models

  * h(theta): Regression-tree point estimate at -33 kPa

# Notes

Prediction target: Volumetric soil water content at -33 kPa.
Figure 2 reports terminal means and within-node standard deviations in volume percent; public
outputs divide the means by 100.
Every comparison is strict less-than, so equality follows the No branch. The cases cover every
leaf and threshold.
A NaN organic-carbon input makes every less-than comparison false and follows the corresponding
No branches; it is not propagated automatically."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_rawls2003_soc_theta33_tree(
    soil_texture: crate::definitions::soil::UsdaTextureClass,
    soil_organic_carbon: f64,
) -> f64 {
    theta_33_tree(soil_texture, soil_organic_carbon)
}
#[cfg(test)]
mod calc_ptf_rawls2003_soc_theta33_tree_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn figure_2_leaf_01_sand() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Sand,
            1f64,
        );
        assert_close(
            result,
            0.108f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_02_loamy_sand() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::LoamySand,
            1f64,
        );
        assert_close(
            result,
            0.151f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_03_sandy_loam_low_corg() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyLoam,
            1f64,
        );
        assert_close(
            result,
            0.204f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_04_corg_1_1_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyLoam,
            1.1f64,
        );
        assert_close(
            result,
            0.244f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_05_corg_2_1_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Sand,
            2.1f64,
        );
        assert_close(
            result,
            0.28f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_06_corg_4_8_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::LoamySand,
            4.8f64,
        );
        assert_close(
            result,
            0.35f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_07_corg_7_7_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Sand,
            7.7f64,
        );
        assert_close(
            result,
            0.394f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_08_sandy_loam_high_corg() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyLoam,
            7.7f64,
        );
        assert_close(
            result,
            0.549f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_09_loam_low_corg() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Loam,
            1f64,
        );
        assert_close(
            result,
            0.272f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_10_corg_1_7_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Loam,
            1.7f64,
        );
        assert_close(
            result,
            0.305f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_11_silt_loam_low_corg() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltLoam,
            1f64,
        );
        assert_close(
            result,
            0.315f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_12_corg_1_5_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltLoam,
            1.5f64,
        );
        assert_close(
            result,
            0.338f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_13_corg_4_2_loam_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Loam,
            4.2f64,
        );
        assert_close(
            result,
            0.353f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_14_corg_4_2_silt_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltLoam,
            4.2f64,
        );
        assert_close(
            result,
            0.393f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_15_corg_8_5_loam_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Loam,
            8.5f64,
        );
        assert_close(
            result,
            0.383f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_16_corg_8_5_silt_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltLoam,
            8.5f64,
        );
        assert_close(
            result,
            0.464f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_17_silty_clay_loam_low_corg() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltyClayLoam,
            4f64,
        );
        assert_close(
            result,
            0.361f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_18_corg_4_2_very_fine_boundary() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltyClayLoam,
            4.2f64,
        );
        assert_close(
            result,
            0.548f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_19_silty_clay() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SiltyClay,
            1f64,
        );
        assert_close(
            result,
            0.397f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_leaf_20_clay() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Clay,
            1f64,
        );
        assert_close(
            result,
            0.426f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_clay_loam_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::ClayLoam,
            1f64,
        );
        assert_close(
            result,
            0.315f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_clay_loam_mid_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::ClayLoam,
            2f64,
        );
        assert_close(
            result,
            0.338f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_clay_loam_mid_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::ClayLoam,
            5f64,
        );
        assert_close(
            result,
            0.353f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_clay_loam_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::ClayLoam,
            9f64,
        );
        assert_close(
            result,
            0.464f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClay,
            1f64,
        );
        assert_close(
            result,
            0.272f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_mid_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClay,
            2f64,
        );
        assert_close(
            result,
            0.305f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_mid_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClay,
            5f64,
        );
        assert_close(
            result,
            0.353f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClay,
            9f64,
        );
        assert_close(
            result,
            0.383f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_loam_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClayLoam,
            1f64,
        );
        assert_close(
            result,
            0.272f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_loam_mid_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClayLoam,
            2f64,
        );
        assert_close(
            result,
            0.305f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_loam_mid_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClayLoam,
            5f64,
        );
        assert_close(
            result,
            0.393f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_sandy_clay_loam_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::SandyClayLoam,
            9f64,
        );
        assert_close(
            result,
            0.464f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_silt_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Silt,
            1f64,
        );
        assert_close(
            result,
            0.315f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_silt_mid_low() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Silt,
            2f64,
        );
        assert_close(
            result,
            0.338f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_silt_mid_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Silt,
            5f64,
        );
        assert_close(
            result,
            0.393f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_2_silt_high() {
        let result = calc_ptf_rawls2003_soc_theta33_tree(
            crate::definitions::soil::UsdaTextureClass::Silt,
            9f64,
        );
        assert_close(
            result,
            0.464f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -1500 kPa with the published regression tree.

# Arguments

  * clay: Clay content by mass. (% mass)
  * sand: Sand content by mass. (% mass)
  * soil_organic_carbon: Soil organic carbon content by mass. (% mass)

# Returns

  * theta_1500: Volumetric soil water content at -1500 kPa. (cm³/cm³)

# Models

  * h(theta): Regression-tree point estimate at -1500 kPa

# Notes

Prediction target: Volumetric soil water content at -1500 kPa.
Figure 3 reports terminal means and within-node standard deviations in volume percent; public
outputs divide the means by 100.
Every comparison is strict less-than, so equality follows the No branch. The cases cover every
leaf and threshold.
NaN numeric inputs make less-than comparisons false and follow the corresponding No branches;
they are not propagated automatically."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_rawls2003_soc_theta1500_tree(
    clay: f64,
    sand: f64,
    soil_organic_carbon: f64,
) -> f64 {
    theta_1500_tree(clay, sand, soil_organic_carbon)
}
#[cfg(test)]
mod calc_ptf_rawls2003_soc_theta1500_tree_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn figure_3_leaf_01_low_corg() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(5f64, 70f64, 1f64);
        assert_close(
            result,
            0.061f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_02_corg_1_5_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(5f64, 70f64, 1.5f64);
        assert_close(
            result,
            0.085f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_03_sand_80_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(5f64, 80f64, 1f64);
        assert_close(
            result,
            0.04f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_04_clay_8_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(8f64, 20f64, 2f64);
        assert_close(
            result,
            0.082f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_05_clay_12_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(12f64, 20f64, 2f64);
        assert_close(
            result,
            0.1f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_06_corg_2_3_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(13f64, 20f64, 2.3f64);
        assert_close(
            result,
            0.11f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_07_corg_6_5_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(13f64, 20f64, 6.5f64);
        assert_close(
            result,
            0.159f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_08_clay_14_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(14f64, 20f64, 5f64);
        assert_close(
            result,
            0.116f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_09_clay_17_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(17f64, 20f64, 5f64);
        assert_close(
            result,
            0.128f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_10_corg_5_8_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(18f64, 20f64, 5.8f64);
        assert_close(
            result,
            0.167f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_11_clay_19_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(19f64, 20f64, 1f64);
        assert_close(
            result,
            0.143f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_12_clay_23_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(23f64, 20f64, 1f64);
        assert_close(
            result,
            0.16f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_13_clay_26_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(26f64, 20f64, 1f64);
        assert_close(
            result,
            0.173f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_14_clay_29_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(29f64, 20f64, 1f64);
        assert_close(
            result,
            0.193f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_15_clay_33_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(33f64, 20f64, 1f64);
        assert_close(
            result,
            0.211f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_16_clay_37_4_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(37.4f64, 20f64, 1f64);
        assert_close(
            result,
            0.229f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_17_clay_44_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(44f64, 20f64, 1f64);
        assert_close(
            result,
            0.253f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_18_clay_48_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(48f64, 20f64, 1f64);
        assert_close(
            result,
            0.275f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_19_clay_54_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(54f64, 20f64, 1f64);
        assert_close(
            result,
            0.296f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn figure_3_leaf_20_clay_67_boundary() {
        let result = calc_ptf_rawls2003_soc_theta1500_tree(67f64, 20f64, 1f64);
        assert_close(
            result,
            0.323f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -33 kPa with the published GMDH polynomial.

# Arguments

  * soil_organic_carbon: Soil organic carbon content by mass. (% mass)
  * clay: Clay content by mass. (% mass)
  * sand: Sand content by mass; clay plus sand must not exceed 100. (% mass)

# Returns

  * theta_33: Volumetric soil water content at -33 kPa. (cm³/cm³)

# Models

  * h(theta): GMDH polynomial point estimate at -33 kPa

# Notes

Prediction target: Volumetric soil water content at -33 kPa.
The polynomial calculates volume percent; the public output divides the result by 100.

# Warnings

Apply only within the source ranges and with clay plus sand no greater than 100%."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_rawls2003_soc_theta33_gmdh(soil_organic_carbon: f64, clay: f64, sand: f64) -> f64 {
    let x = -0.837531f64 + 0.430183f64 * soil_organic_carbon;
    let y = -1.40744f64 + 0.0661969f64 * clay;
    let z = -1.51866f64 + 0.0393284f64 * sand;
    let x_squared = x.powi(2);
    let x_cubed = x.powi(3);
    let y_squared = y.powi(2);
    let y_cubed = y.powi(3);
    let z_squared = z.powi(2);
    let z_cubed = z.powi(3);
    let xy = x * y;
    let polynomial = 0.0461615f64 + 0.290955f64 * x - 0.0496845f64 * x_squared
        + 0.00704802f64 * x_cubed
        + 0.269101f64 * y
        - 0.176528f64 * xy
        + 0.0543138f64 * x_squared * y
        + 0.1982f64 * y_squared
        - 0.060699f64 * y_cubed
        - 0.320249f64 * z
        - 0.0111693f64 * x_squared * z
        + 0.14104f64 * y * z
        + 0.0657345f64 * xy * z
        - 0.102026f64 * y_squared * z
        - 0.04012f64 * z_squared
        + 0.160838f64 * x * z_squared
        - 0.121392f64 * y * z_squared
        - 0.0616676f64 * z_cubed;
    let theta_33_volume_percent = 29.7528f64 + 10.3544f64 * polynomial;
    theta_33_volume_percent / 100.0f64
}
#[cfg(test)]
mod calc_ptf_rawls2003_soc_theta33_gmdh_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn calculated_diagnostic_probe() {
        let result = calc_ptf_rawls2003_soc_theta33_gmdh(1f64, 20f64, 60f64);
        assert_close(
            result,
            0.24651660127906824f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn calculated_high_carbon_probe() {
        let result = calc_ptf_rawls2003_soc_theta33_gmdh(10f64, 20f64, 60f64);
        assert_close(
            result,
            0.3652565811155751f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn calculated_varied_predictors_probe() {
        let result = calc_ptf_rawls2003_soc_theta33_gmdh(5f64, 35f64, 40f64);
        assert_close(
            result,
            0.3580247775824793f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
#[doc = r"Estimate volumetric water content at -1500 kPa with the published GMDH polynomial.

# Arguments

  * soil_organic_carbon: Soil organic carbon content by mass. (% mass)
  * clay: Clay content by mass. (% mass)
  * sand: Sand content by mass; clay plus sand must not exceed 100. (% mass)

# Returns

  * theta_1500: Volumetric soil water content at -1500 kPa. (cm³/cm³)

# Models

  * h(theta): GMDH polynomial point estimate at -1500 kPa

# Notes

Prediction target: Volumetric soil water content at -1500 kPa.
The polynomial calculates volume percent; the public output divides the result by 100.

# Warnings

Apply only within the source ranges and with clay plus sand no greater than 100%."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_rawls2003_soc_theta1500_gmdh(
    soil_organic_carbon: f64,
    clay: f64,
    sand: f64,
) -> f64 {
    let x = -0.837531f64 + 0.430183f64 * soil_organic_carbon;
    let y = -1.40744f64 + 0.0661969f64 * clay;
    let z = -1.51866f64 + 0.0393284f64 * sand;
    let x_squared = x.powi(2);
    let x_cubed = x.powi(3);
    let y_squared = y.powi(2);
    let y_cubed = y.powi(3);
    let z_squared = z.powi(2);
    let z_cubed = z.powi(3);
    let xy = x * y;
    let polynomial = 0.06865f64 + 0.108713f64 * x - 0.0157225f64 * x_squared
        + 0.00102805f64 * x_cubed
        + 0.886569f64 * y
        - 0.223581f64 * xy
        + 0.0126379f64 * x_squared * y
        - 0.017059f64 * y_squared
        + 0.0135266f64 * x * y_squared
        - 0.0334434f64 * y_cubed
        - 0.0535182f64 * z
        - 0.0354271f64 * x * z
        - 0.00261313f64 * x_squared * z
        - 0.154563f64 * y * z
        - 0.0160219f64 * xy * z
        - 0.0400606f64 * y_squared * z
        - 0.104875f64 * z_squared
        + 0.0159857f64 * x * z_squared
        - 0.0671656f64 * y * z_squared
        - 0.0260699f64 * z_cubed;
    let theta_1500_volume_percent = 14.2568f64 + 7.36318f64 * polynomial;
    theta_1500_volume_percent / 100.0f64
}
#[cfg(test)]
mod calc_ptf_rawls2003_soc_theta1500_gmdh_tests {
    use super::*;
    use crate::test_support::assert_close;
    #[test]
    fn calculated_diagnostic_probe() {
        let result = calc_ptf_rawls2003_soc_theta1500_gmdh(1f64, 20f64, 60f64);
        assert_close(
            result,
            0.12978036954714564f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn calculated_high_carbon_probe() {
        let result = calc_ptf_rawls2003_soc_theta1500_gmdh(10f64, 20f64, 60f64);
        assert_close(
            result,
            0.1477870187688732f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
    #[test]
    fn calculated_varied_predictors_probe() {
        let result = calc_ptf_rawls2003_soc_theta1500_gmdh(15f64, 60f64, 20f64);
        assert_close(
            result,
            0.22146307675008264f64,
            0.001f64,
            0f64,
            "volumetric_water_content",
            "volume_fraction",
            "registry",
        );
    }
}
