// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Varallyai et al. (1982), water-retention parameter regressions for Hungarian soils.

# Reference

Varallyai, D., Raikai, K., Mironenko, Ye. V., Pachepskiy, Ya. A., & Scherbakov, R. A. (1982). A
mathematical description of basic water-physical soil characteristics. Pochvovedenie, (4),
77-89.

# Territory

Hungary, mainly the Hungarian Plain

# Dataset

Undisturbed samples from 559 genetic horizons in 160 soil profiles; the meadow-series
regressions used 68 samples and the chernozem comparison used 108 samples."]

#[cfg(test)]
fn resolved_tolerance(expected: f64, absolute: f64, relative: f64) -> f64 {
    absolute
        .max(relative * expected.abs())
        .max(0.00000000000001f64)
}
#[cfg(test)]
fn assert_close(
    actual: f64,
    expected: f64,
    absolute: f64,
    relative: f64,
    quantity: &str,
    unit: &str,
    source: &str,
) {
    let difference = (actual - expected).abs();
    let tolerance = resolved_tolerance(expected, absolute, relative);
    assert!(
        difference <= tolerance,
        "actual={actual}, expected={expected}, difference={difference}, tolerance={tolerance}, quantity={quantity}, unit={unit}, source={source}"
    );
}
#[cfg(test)]
mod comparator_tests {
    use super::*;
    #[test]
    fn accepts_below_and_rejects_above_tolerance() {
        for expected in [0.0, 2.0, -2.0] {
            let tolerance = resolved_tolerance(expected, 0.001, 0.01);
            assert!((expected + tolerance * 0.5 - expected).abs() <= tolerance);
            assert!((expected + tolerance * 2.0 - expected).abs() > tolerance);
        }
    }
}
#[doc = r"Results returned by `calc_ptf_varallyai1982_meadow`."]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Varallyai1982Parameters {
    #[doc = r"Upper-asymptote water content parameter of equation (9). (vol.%)"]
    pub theta_0: f64,
    #[doc = r"Shape parameter of equation (9). (dimensionless)"]
    pub m: f64,
    #[doc = r"Base-10 logarithm of the equation (9) suction-scale parameter psi_*, with suction expressed in
centimetres of water. (dimensionless)"]
    pub pf_star: f64,
}
#[doc = r"Estimate equation (9) water-retention parameters for meadow-series soils.

# Arguments

  * bulk_density: Undisturbed-soil bulk density. (g/cm^3)
  * fine_sand_fraction: Mass fraction in the 0.25-0.05 mm particle-size class. (fraction)
  * fine_fraction: Fine-particle mass fraction reported as particles smaller than 0.002 mm.
    (fraction)

# Returns

A [`Varallyai1982Parameters`].

# Territory

Hungary, mainly the Hungarian Plain

# Models

  * h(theta): theta = theta_0 / (1 + (psi / psi_*)^m)

# Notes

Prediction target: Parameters of the equation (9) water-retention model.
Equation (14) was fitted to 68 meadow-series soil samples.
S and C are fractions of one, while bulk density is in g/cm^3.
The source reports 95% relative errors of 14% for theta_0, 34% for m, and 25% for pF_*.

# Warnings

Use is described as approximate by the source.
The source does not report exact calibration ranges; avoid extrapolation beyond comparable
Hungarian meadow-series soils."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_varallyai1982_meadow(
    bulk_density: f64,
    fine_sand_fraction: f64,
    fine_fraction: f64,
) -> Varallyai1982Parameters {
    let theta_0 = -8.78f64 * bulk_density.powi(2) + 14.46f64 * fine_fraction.powi(2) + 62.85f64;
    let m = 0.576f64 * fine_sand_fraction.powi(2) - 1.434f64 * fine_sand_fraction * fine_fraction
        + 0.156f64;
    let pf_star =
        -1.702f64 * fine_sand_fraction + 1.103f64 * bulk_density * fine_fraction + 3.749f64;
    Varallyai1982Parameters {
        theta_0,
        m,
        pf_star,
    }
}
#[cfg(test)]
mod calc_ptf_varallyai1982_meadow_tests {
    use super::*;
    #[test]
    fn representative_review_case() {
        let result = calc_ptf_varallyai1982_meadow(1.4f64, 0.3f64, 0.25f64);
        assert_close(
            result.theta_0,
            46.54495f64,
            0.1f64,
            0f64,
            "volumetric_water_content",
            "vol.%",
            "registry",
        );
        assert_close(
            result.m,
            0.10029f64,
            0.001f64,
            0f64,
            "varallyai_m",
            "dimensionless",
            "registry",
        );
        assert_close(
            result.pf_star,
            3.62445f64,
            0.001f64,
            0f64,
            "varallyai_pf_star",
            "dimensionless",
            "registry",
        );
    }
}
#[doc = r"Estimate equation (9) water-retention parameters for chernozem A horizons.

# Arguments

  * bulk_density: Undisturbed-soil bulk density. (g/cm^3)
  * fine_fraction: Fine-particle mass fraction reported as particles smaller than 0.002 mm.
    (fraction)

# Returns

A [`Varallyai1982Parameters`].

# Territory

Hungary, mainly the Hungarian Plain

# Models

  * h(theta): theta = theta_0 / (1 + (psi / psi_*)^m)

# Notes

Prediction target: Parameters of the equation (9) water-retention model for chernozem A
horizons.
Equation (15) applies to chernozem A horizons.
The source reports 95% relative errors of 10% for theta_0, 29% for m, and 18% for pF_*.

# Warnings

Use is described as approximate by the source.
The source does not report exact calibration ranges; avoid extrapolation beyond comparable
Hungarian chernozem A horizons."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_varallyai1982_chernozem_a(
    bulk_density: f64,
    fine_fraction: f64,
) -> Varallyai1982Parameters {
    let theta_0 = -56.40f64 * bulk_density + 20.50f64 * fine_fraction + 123.79f64;
    let m = 0.336f64 * bulk_density - 0.053f64;
    let pf_star = 4.701f64 * bulk_density * fine_fraction + 1.513f64 * bulk_density - 0.417f64;
    Varallyai1982Parameters {
        theta_0,
        m,
        pf_star,
    }
}
#[cfg(test)]
mod calc_ptf_varallyai1982_chernozem_a_tests {
    use super::*;
    #[test]
    fn representative_review_case() {
        let result = calc_ptf_varallyai1982_chernozem_a(1.4f64, 0.35f64);
        assert_close(
            result.theta_0,
            52.005f64,
            0.1f64,
            0f64,
            "volumetric_water_content",
            "vol.%",
            "registry",
        );
        assert_close(
            result.m,
            0.4174f64,
            0.001f64,
            0f64,
            "varallyai_m",
            "dimensionless",
            "registry",
        );
        assert_close(
            result.pf_star,
            4.00469f64,
            0.001f64,
            0f64,
            "varallyai_pf_star",
            "dimensionless",
            "registry",
        );
    }
}
#[doc = r"Estimate equation (9) water-retention parameters for chernozem B horizons.

# Arguments

  * bulk_density: Undisturbed-soil bulk density. (g/cm^3)
  * fine_fraction: Fine-particle mass fraction reported as particles smaller than 0.002 mm.
    (fraction)

# Returns

A [`Varallyai1982Parameters`].

# Territory

Hungary, mainly the Hungarian Plain

# Models

  * h(theta): theta = theta_0 / (1 + (psi / psi_*)^m)

# Notes

Prediction target: Parameters of the equation (9) water-retention model for chernozem B
horizons.
Equation (16) applies to chernozem B horizons.
The source reports 95% relative errors of 11% for theta_0, 34% for m, and 18% for pF_*.

# Warnings

Use is described as approximate by the source.
The source does not report exact calibration ranges; avoid extrapolation beyond comparable
Hungarian chernozem B horizons."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_varallyai1982_chernozem_b(
    bulk_density: f64,
    fine_fraction: f64,
) -> Varallyai1982Parameters {
    let theta_0 = -62.20f64 * bulk_density - 49.14f64 * fine_fraction.powi(2) + 140.70f64;
    let m = 0.635f64 * bulk_density - 0.482f64;
    let pf_star = 4.270f64 * bulk_density * fine_fraction + 3.509f64 * bulk_density - 3.075f64;
    Varallyai1982Parameters {
        theta_0,
        m,
        pf_star,
    }
}
#[cfg(test)]
mod calc_ptf_varallyai1982_chernozem_b_tests {
    use super::*;
    #[test]
    fn representative_review_case() {
        let result = calc_ptf_varallyai1982_chernozem_b(1.4f64, 0.35f64);
        assert_close(
            result.theta_0,
            47.60035f64,
            0.1f64,
            0f64,
            "volumetric_water_content",
            "vol.%",
            "registry",
        );
        assert_close(
            result.m,
            0.407f64,
            0.001f64,
            0f64,
            "varallyai_m",
            "dimensionless",
            "registry",
        );
        assert_close(
            result.pf_star,
            3.9299f64,
            0.001f64,
            0f64,
            "varallyai_pf_star",
            "dimensionless",
            "registry",
        );
    }
}
#[doc = r"Estimate equation (9) water-retention parameters for chernozem C horizons.

# Arguments

  * bulk_density: Undisturbed-soil bulk density. (g/cm^3)
  * fine_fraction: Fine-particle mass fraction reported as particles smaller than 0.002 mm.
    (fraction)

# Returns

A [`Varallyai1982Parameters`].

# Territory

Hungary, mainly the Hungarian Plain

# Models

  * h(theta): theta = theta_0 / (1 + (psi / psi_*)^m)

# Notes

Prediction target: Parameters of the equation (9) water-retention model for chernozem C
horizons.
Equation (17) applies to chernozem C horizons.
The source reports 95% relative errors of 7% for theta_0, 22% for m, and 11% for pF_*.

# Warnings

Use is described as approximate by the source.
The source does not report exact calibration ranges; avoid extrapolation beyond comparable
Hungarian chernozem C horizons."]
#[cfg_attr(feature = "inline", inline)]
#[must_use]
pub fn calc_ptf_varallyai1982_chernozem_c(
    bulk_density: f64,
    fine_fraction: f64,
) -> Varallyai1982Parameters {
    let theta_0 = -46.80f64 * bulk_density + 115.39f64;
    let m = 0.439f64 * bulk_density * fine_fraction + 0.625f64;
    let pf_star =
        3.268f64 * bulk_density * fine_fraction + 0.865f64 * bulk_density.powi(2) + 0.301f64;
    Varallyai1982Parameters {
        theta_0,
        m,
        pf_star,
    }
}
#[cfg(test)]
mod calc_ptf_varallyai1982_chernozem_c_tests {
    use super::*;
    #[test]
    fn representative_review_case() {
        let result = calc_ptf_varallyai1982_chernozem_c(1.4f64, 0.35f64);
        assert_close(
            result.theta_0,
            49.87f64,
            0.1f64,
            0f64,
            "volumetric_water_content",
            "vol.%",
            "registry",
        );
        assert_close(
            result.m,
            0.84011f64,
            0.001f64,
            0f64,
            "varallyai_m",
            "dimensionless",
            "registry",
        );
        assert_close(
            result.pf_star,
            3.59772f64,
            0.001f64,
            0f64,
            "varallyai_pf_star",
            "dimensionless",
            "registry",
        );
    }
}
