// @generated by ptfkit-codegen; DO NOT EDIT.

#![doc = r"Weber et al. (2020), compiled international soil hydraulic data.

# Reference

Weber, T. K. D., Finkel, M., da Conceicao Goncalves, M., Vereecken, H., & Diamantopoulos, E.
(2020). Pedotransfer function for the Brunswick soil hydraulic property model and comparison to
the van Genuchten-Mualem model. Water Resources Research, 56, e2019WR026820.
DOI: 10.1029/2019WR026820 (https://doi.org/10.1029/2019WR026820)

# Territory

Portuguese, German, UNSODA, and Vereecken soil data collections

# Dataset

A compilation of 1,729 samples with water-retention and hydraulic-conductivity data; regression
data set DS1 contained 392 of the 402 retained samples, DS2 was used for tau, DS3 contained 359
samples for K_snc, and 10 samples were held out as DS4."]

#[doc = r"Results returned by `calc_ptf_weber2020`."]
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Weber2020PTFResult {
    #[doc = r"Saturated water content of the Brunswick noncapillary pore space. (dimensionless)"]
    pub theta_snc_bw: f64,
    #[doc = r"Saturated water content of the Brunswick capillary pore space. (dimensionless)"]
    pub theta_sc_bw: f64,
    #[doc = r"Brunswick-VGM inverse pressure-head scale parameter. (cm^-1)"]
    pub alpha_bw: f64,
    #[doc = r"Brunswick-VGM pore-size distribution shape parameter. (dimensionless)"]
    pub n_bw: f64,
    #[doc = r"Brunswick capillary hydraulic-conductivity shape parameter. (dimensionless)"]
    pub tau_bw: f64,
    #[doc = r"Saturated capillary hydraulic conductivity. (cm d^-1)"]
    pub k_sc_bw: f64,
    #[doc = r"Saturated noncapillary hydraulic conductivity. (cm d^-1)"]
    pub k_snc_bw: f64,
}
#[doc = r"Convert VGM parameters to Brunswick-VGM parameters.

# Arguments

  * theta_r_vgm: VGM residual volumetric water content. (dimensionless)
  * theta_s_vgm: VGM saturated volumetric water content. (dimensionless)
  * alpha_vgm: VGM inverse pressure-head scale parameter. (cm^-1)
  * n_vgm: VGM pore-size distribution shape parameter. (dimensionless)
  * tau_vgm: VGM hydraulic-conductivity shape parameter. (dimensionless)
  * k_s_vgm: VGM saturated hydraulic conductivity. (cm d^-1)

# Returns

A [`Weber2020PTFResult`].

# Models

  * h(theta): Brunswick model with the van Genuchten capillary saturation function
  * k(h): Brunswick capillary, noncapillary, and isothermal vapor conductivity model

# Notes

Prediction target: Seven Brunswick-VGM soil hydraulic model parameters from six VGM parameters.
Regression coefficients are the York-regression estimates in Table 3; parenthesized standard
errors are not part of the prediction.
Input domains reproduce the parameter-estimation bounds in Table 1 and are not stated as a
validated application domain.
The source recommends the median K_snc value as a provisional parsimonious estimate requiring
further research.

# Warnings

The DS2 inequality is treated as a source typographical error; the tau regression is interpreted
as being based on nonpositive tau_vgm values."]
#[must_use]
pub fn calc_ptf_weber2020(
    theta_r_vgm: f64,
    theta_s_vgm: f64,
    alpha_vgm: f64,
    n_vgm: f64,
    tau_vgm: f64,
    k_s_vgm: f64,
) -> Weber2020PTFResult {
    let theta_snc_bw = (-(0.00158f64)) + ((1.285f64) * (theta_r_vgm));
    let theta_s_bw = (0.00189f64) + ((0.993f64) * (theta_s_vgm));
    let theta_sc_bw = (theta_s_bw) - (theta_snc_bw);
    let alpha_bw = (10f64).powf((-(0.0206f64)) + ((0.986f64) * ((alpha_vgm).log10())));
    let n_bw = (1f64) + ((10f64).powf((0.0642f64) + ((0.933f64) * (((n_vgm) - (1f64)).log10()))));
    let tau_vgm_constrained = (tau_vgm).min(0f64);
    let tau_bw = (0.0295f64) + ((1.833f64) * (tau_vgm_constrained));
    let k_sc_bw = (10f64).powf((0.116f64) + ((1.06f64) * ((k_s_vgm).log10())));
    let k_snc_bw = (10f64).powf(-(1.72f64));
    Weber2020PTFResult {
        theta_snc_bw,
        theta_sc_bw,
        alpha_bw,
        n_bw,
        tau_bw,
        k_sc_bw,
        k_snc_bw,
    }
}
#[cfg(test)]
mod tests {
    use super::*;
    fn assert_close(actual: f64, expected: f64, atol: f64, rtol: f64) {
        assert!(
            (actual - expected).abs() <= atol + rtol * expected.abs(),
            "actual {actual} != expected {expected}"
        );
    }
    #[test]
    fn representative_vgm_parameters() {
        let result = calc_ptf_weber2020(0.05f64, 0.45f64, 0.02f64, 1.6f64, -0.5f64, 100f64);
        assert_close(
            result.theta_snc_bw,
            0.06267f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.theta_sc_bw,
            0.38607f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.alpha_bw,
            0.0201472407335197f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.n_bw,
            1.71980542683289f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.tau_bw,
            -0.887f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.k_sc_bw,
            172.186857498601f64,
            0.000000000001f64,
            0.000000000001f64,
        );
        assert_close(
            result.k_snc_bw,
            0.0190546071796325f64,
            0.000000000001f64,
            0.000000000001f64,
        );
    }
}
