use crate::{
    model::Entry,
    output::GeneratedFile,
    render::{Render, Writer, markdown},
    targets::python::natural_sort_key,
};

pub(crate) fn render(entries: &[Entry]) -> Vec<GeneratedFile> {
    let mut entries = entries.iter().collect::<Vec<_>>();
    entries.sort_by_key(|entry| natural_sort_key(&entry.slug));

    let mut files = vec![markdown::markdown_file("index.md", |writer| {
        IndexPage { entries: &entries }.render(writer);
    })];
    for entry in entries {
        files.push(markdown::markdown_file(
            format!("{}.md", entry.slug),
            |writer| ModulePage { entry }.render(writer),
        ));
    }
    files
}

struct IndexPage<'a> {
    entries: &'a [&'a Entry],
}

impl Render for IndexPage<'_> {
    fn render(&self, writer: &mut Writer) {
        markdown::generated_frontmatter(writer, |writer| {
            writer.line("title: Python API reference");
        });
        writer.write(
            "# Python API reference\n\nptfkit's Python API is organized around public source modules.\n\n## Modules\n\n",
        );
        for entry in self.entries {
            ModuleReference { entry }.render(writer);
        }
    }
}

struct ModulePage<'a> {
    entry: &'a Entry,
}

impl Render for ModulePage<'_> {
    fn render(&self, writer: &mut Writer) {
        let slug = &self.entry.slug;
        let module = format!("ptfkit.{slug}");
        markdown::generated_frontmatter(writer, |writer| {
            writer.line(format_args!("title: Python module {module}"));
            writer.line(format_args!("nav-title: {module}"));
        });
        writer.line(format_args!("::: {module}"));
    }
}

struct ModuleReference<'a> {
    entry: &'a Entry,
}

impl Render for ModuleReference<'_> {
    fn render(&self, writer: &mut Writer) {
        let slug = &self.entry.slug;
        let summary = &self.entry.spec.source.summary;
        writer.line(format_args!("- [`ptfkit.{slug}`]({slug}.md) — {summary}"));
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::model::PythonGeneration;

    use super::*;

    fn rendered_files() -> Vec<GeneratedFile> {
        let entries = crate::test_support::entries();
        render(&entries)
    }

    fn contents<'a>(files: &'a [GeneratedFile], path: &str) -> &'a str {
        &files
            .iter()
            .find(|file| file.path == Path::new(path))
            .unwrap_or_else(|| panic!("missing generated file {path}"))
            .contents
    }

    #[test]
    fn renders_one_page_for_each_source_module() {
        let entries = crate::test_support::entries();
        let files = render(&entries);
        let index = contents(&files, "index.md");

        assert_eq!(files.len(), entries.len() + 1);
        snapbox::assert_data_eq!(
            index,
            snapbox::file!["../../fixtures/expected/reference/python/index.md"]
        );
        snapbox::assert_data_eq!(
            contents(&files, "example10.md"),
            snapbox::str![
                "---\n# @generated by ptfkit-codegen; DO NOT EDIT.\n\ntitle: Python module ptfkit.example10\nnav-title: ptfkit.example10\n---\n\n::: ptfkit.example10\n\n"
            ]
        );
        snapbox::assert_data_eq!(
            contents(&files, "example2.md"),
            snapbox::str![
                "---\n# @generated by ptfkit-codegen; DO NOT EDIT.\n\ntitle: Python module ptfkit.example2\nnav-title: ptfkit.example2\n---\n\n::: ptfkit.example2\n\n"
            ]
        );
    }

    #[test]
    fn includes_intentional_manual_public_modules() {
        let mut entries = crate::test_support::entries();
        let manual = entries
            .iter_mut()
            .find(|entry| entry.slug == "example2")
            .unwrap();
        manual.spec.generation.public_python = PythonGeneration::Manual;
        let files = render(&entries);

        assert!(contents(&files, "example2.md").contains("::: ptfkit.example2"));
    }

    #[test]
    fn excludes_private_implementation_modules() {
        let files = rendered_files();
        let index = contents(&files, "index.md");

        assert!(!index.contains("_ptfkit"));
        assert!(!index.contains("__init__"));
        assert!(files.iter().all(|file| {
            file.path
                .extension()
                .is_some_and(|extension| extension == "md")
        }));
    }
}
