use crate::{
    model::Entry,
    output::GeneratedFile,
    render::{Render, Writer, markdown},
    targets::python::natural_sort_key,
};

pub(crate) fn render(entries: &[Entry]) -> Vec<GeneratedFile> {
    let mut entries = entries.iter().collect::<Vec<_>>();
    entries.sort_by_key(|entry| natural_sort_key(&entry.slug));

    let mut files = vec![markdown::markdown_file("index.md", |writer| {
        IndexPage { entries: &entries }.render(writer);
    })];
    for entry in entries {
        files.push(markdown::markdown_file(
            format!("{}.md", entry.slug),
            |writer| ModulePage { entry }.render(writer),
        ));
    }
    files
}

struct IndexPage<'a> {
    entries: &'a [&'a Entry],
}

impl Render for IndexPage<'_> {
    fn render(&self, writer: &mut Writer) {
        markdown::generated_frontmatter(writer, |writer| {
            writer.line("title: Python API reference");
        });
        writer.write(
            "# Python API reference\n\nptfkit's Python API is organized around public source modules.\n\n## Modules\n\n",
        );
        for entry in self.entries {
            ModuleReference { entry }.render(writer);
        }
    }
}

struct ModulePage<'a> {
    entry: &'a Entry,
}

impl Render for ModulePage<'_> {
    fn render(&self, writer: &mut Writer) {
        let slug = &self.entry.slug;
        let module = format!("ptfkit.{slug}");
        markdown::generated_frontmatter(writer, |writer| {
            writer.line(format_args!("title: Python module {module}"));
            writer.line(format_args!("nav-title: {module}"));
        });
        writer.line(format_args!("::: {module}"));
    }
}

struct ModuleReference<'a> {
    entry: &'a Entry,
}

impl Render for ModuleReference<'_> {
    fn render(&self, writer: &mut Writer) {
        let slug = &self.entry.slug;
        let summary = &self.entry.spec.source.summary;
        writer.line(format_args!("- [`ptfkit.{slug}`]({slug}.md) — {summary}"));
    }
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use crate::model::PythonGeneration;

    use super::*;

    fn rendered_files() -> Vec<GeneratedFile> {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("codegen directory has a repository parent");
        let entries = crate::specs::load(root).expect("repository specifications load");
        render(&entries)
    }

    fn contents<'a>(files: &'a [GeneratedFile], path: &str) -> &'a str {
        &files
            .iter()
            .find(|file| file.path == Path::new(path))
            .unwrap_or_else(|| panic!("missing generated file {path}"))
            .contents
    }

    #[test]
    fn renders_one_page_for_each_source_module() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("codegen directory has a repository parent");
        let entries = crate::specs::load(root).expect("repository specifications load");
        let files = render(&entries);
        let index = contents(&files, "index.md");

        assert!(index.starts_with(
            "---\n# @generated by ptfkit-codegen; DO NOT EDIT.\n\ntitle: Python API reference\n---\n"
        ));
        assert_eq!(files.len(), entries.len() + 1);

        for entry in &entries {
            let module = format!("ptfkit.{}", entry.slug);
            assert!(index.contains(&format!("[`{module}`]({}.md)", entry.slug)));

            let page = contents(&files, &format!("{}.md", entry.slug));
            assert!(page.starts_with(&format!(
                "---\n# @generated by ptfkit-codegen; DO NOT EDIT.\n\ntitle: Python module {module}\nnav-title: {module}\n---\n"
            )));
            assert!(page.contains(&format!("::: {module}")));
        }
    }

    #[test]
    fn includes_intentional_manual_public_modules() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("codegen directory has a repository parent");
        let mut entries = crate::specs::load(root).expect("repository specifications load");
        entries[0].spec.generation.public_python = PythonGeneration::Manual;
        let files = render(&entries);

        assert!(contents(&files, "ahuja1984.md").contains("::: ptfkit.ahuja1984"));
    }

    #[test]
    fn excludes_private_implementation_modules() {
        let files = rendered_files();
        let index = contents(&files, "index.md");

        assert!(!index.contains("_ptfkit"));
        assert!(!index.contains("__init__"));
        assert!(files.iter().all(|file| {
            file.path
                .extension()
                .is_some_and(|extension| extension == "md")
        }));
    }
}
