/* @generated by ptfkit-codegen; DO NOT EDIT. */

#include <ptfkit/ahuja1984.h>
#include "support/close_enough.h"

int main() {
    {
        const double result = calc_ptf_ahuja1984(0.45, 0.25, 100.0, 4.0);
        assert_close(result, 0.16, 0.00001, 0.01, "saturated_hydraulic_conductivity", "cm/h",
                     "registry");
    }
    {
        const double result = calc_ptf_ahuja1984(0.5, 0.2, 100.0, 5.0);
        assert_close(result, 0.243, 0.00001, 0.01, "saturated_hydraulic_conductivity", "cm/h",
                     "registry");
    }
    return 0;
}
