/* @generated by ptfkit-codegen; DO NOT EDIT. */

#include <ptfkit/clapp1978.h>
#include "close_enough.h"

int main() {
    {
        const clapp1978_parameters result = calc_ptf_clapp1978(clapp1978_usda_texture_class_sand);
        assert_exact(result.b, 4.05);
        assert_exact(result.saturation_suction, 3.5);
        assert_exact(result.wetting_front_suction, 4.66);
        assert_exact(result.saturated_water_content, 0.395);
        assert_exact(result.saturated_hydraulic_conductivity, 1.056);
        assert_exact(result.sorptivity, 1.52);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_loamy_sand);
        assert_exact(result.b, 4.38);
        assert_exact(result.saturation_suction, 1.78);
        assert_exact(result.wetting_front_suction, 2.38);
        assert_exact(result.saturated_water_content, 0.41);
        assert_exact(result.saturated_hydraulic_conductivity, 0.938);
        assert_exact(result.sorptivity, 1.04);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_sandy_loam);
        assert_exact(result.b, 4.9);
        assert_exact(result.saturation_suction, 7.18);
        assert_exact(result.wetting_front_suction, 9.52);
        assert_exact(result.saturated_water_content, 0.435);
        assert_exact(result.saturated_hydraulic_conductivity, 0.208);
        assert_exact(result.sorptivity, 1.03);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_silt_loam);
        assert_exact(result.b, 5.3);
        assert_exact(result.saturation_suction, 56.6);
        assert_exact(result.wetting_front_suction, 75.3);
        assert_exact(result.saturated_water_content, 0.485);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0432);
        assert_exact(result.sorptivity, 1.26);
    }
    {
        const clapp1978_parameters result = calc_ptf_clapp1978(clapp1978_usda_texture_class_loam);
        assert_exact(result.b, 5.39);
        assert_exact(result.saturation_suction, 14.6);
        assert_exact(result.wetting_front_suction, 20.0);
        assert_exact(result.saturated_water_content, 0.451);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0417);
        assert_exact(result.sorptivity, 0.693);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_sandy_clay_loam);
        assert_exact(result.b, 7.12);
        assert_exact(result.saturation_suction, 8.63);
        assert_exact(result.wetting_front_suction, 11.7);
        assert_exact(result.saturated_water_content, 0.42);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0378);
        assert_exact(result.sorptivity, 0.488);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_silty_clay_loam);
        assert_exact(result.b, 7.75);
        assert_exact(result.saturation_suction, 14.6);
        assert_exact(result.wetting_front_suction, 19.7);
        assert_exact(result.saturated_water_content, 0.477);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0102);
        assert_exact(result.sorptivity, 0.31);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_clay_loam);
        assert_exact(result.b, 8.52);
        assert_exact(result.saturation_suction, 36.1);
        assert_exact(result.wetting_front_suction, 48.1);
        assert_exact(result.saturated_water_content, 0.476);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0147);
        assert_exact(result.sorptivity, 0.537);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_sandy_clay);
        assert_exact(result.b, 10.4);
        assert_exact(result.saturation_suction, 6.16);
        assert_exact(result.wetting_front_suction, 8.18);
        assert_exact(result.saturated_water_content, 0.426);
        assert_exact(result.saturated_hydraulic_conductivity, 0.013);
        assert_exact(result.sorptivity, 0.223);
    }
    {
        const clapp1978_parameters result =
            calc_ptf_clapp1978(clapp1978_usda_texture_class_silty_clay);
        assert_exact(result.b, 10.4);
        assert_exact(result.saturation_suction, 17.4);
        assert_exact(result.wetting_front_suction, 23.0);
        assert_exact(result.saturated_water_content, 0.492);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0062);
        assert_exact(result.sorptivity, 0.242);
    }
    {
        const clapp1978_parameters result = calc_ptf_clapp1978(clapp1978_usda_texture_class_clay);
        assert_exact(result.b, 11.4);
        assert_exact(result.saturation_suction, 18.6);
        assert_exact(result.wetting_front_suction, 24.3);
        assert_exact(result.saturated_water_content, 0.482);
        assert_exact(result.saturated_hydraulic_conductivity, 0.0077);
        assert_exact(result.sorptivity, 0.268);
    }
    return 0;
}
