/* @generated by ptfkit-codegen; DO NOT EDIT. */

#include <ptfkit/cosby1984.h>
#include "close_enough.h"

int main() {
    {
        const cosby1984_univariate_ptf_result result =
            calc_ptf_cosby1984_univariate(50.0, 30.0, 20.0);
        assert_close_enough(result.mean_b, 6.09, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_psi_s, 1.225, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_k_sat, -0.119, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_theta_s, 42.6, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_b, 2.34, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_log_k_sat, 0.5553, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_theta_s, 6.27, 0.000000000001, 0.000000000001);
    }
    {
        const cosby1984_univariate_ptf_result result =
            calc_ptf_cosby1984_univariate(80.0, 15.0, 5.0);
        assert_close_enough(result.mean_b, 3.705, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_psi_s, 0.832, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_k_sat, 0.34, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_theta_s, 38.82, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_b, 1.59, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_log_k_sat, 0.50715, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_theta_s, 7.365, 0.000000000001, 0.000000000001);
    }
    {
        const cosby1984_univariate_ptf_result result =
            calc_ptf_cosby1984_univariate_usda_texture(PTFKIT_USDA_TEXTURE_LOAM);
        assert_close_enough(result.mean_b, 5.613, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_psi_s, 1.3429, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_log_k_sat, -0.2567, 0.000000000001, 0.000000000001);
        assert_close_enough(result.mean_theta_s, 43.734, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_b, 2.19, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_log_k_sat, 0.59382, 0.000000000001, 0.000000000001);
        assert_close_enough(result.sd_theta_s, 6.489, 0.000000000001, 0.000000000001);
    }
    return 0;
}
