/* @generated by ptfkit-codegen; DO NOT EDIT. */

#include <ptfkit/hodnett2002.h>
#include "support/close_enough.h"

int main() {
    {
        const hodnett2002_ptf_result result =
            calc_ptf_hodnett2002(39.2, 24.2, 36.7, 1.4, 1.2, 15.9, 5.85);
        assert_close(result.alpha, 0.245183615037873, 0.00001, 0.0, "van_genuchten_alpha",
                     "inverse_kilopascal", "registry", "calibration_dataset_mean_properties");
        assert_close(result.n, 1.36739326352383, 0.001, 0.0, "van_genuchten_n", "dimensionless",
                     "registry", "calibration_dataset_mean_properties");
        assert_close(result.theta_s, 0.4993353, 0.001, 0.0, "volumetric_water_content",
                     "volume_fraction", "registry", "calibration_dataset_mean_properties");
        assert_close(result.theta_r, 0.21344216, 0.001, 0.0, "volumetric_water_content",
                     "volume_fraction", "registry", "calibration_dataset_mean_properties");
    }
    return 0;
}
