site_name: ptfkit
site_description: Specification-driven collection of published pedotransfer functions for estimating soil hydraulic properties in Python, Rust, C, and C++.
site_url: https://agrodt.github.io/ptfkit/
repo_url: https://github.com/AgroDT/ptfkit
repo_name: AgroDT/ptfkit
docs_dir: src
site_dir: dist

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.tabs

plugins:
  - awesome-nav
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [../targets/ptfkit-py/src]
          options:
            docstring_section_style: spacy
            docstring_style: google
            separate_signature: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            overloads_only: true
            summary: true
  - minify:
      minify_html: true

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

hooks:
  - hooks.py

extra_javascript:
  - js/katex.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0/dist/katex.min.css
