[windows]
set shell := ["powershell.exe", "-NoLogo", "-Command"]

default:
	@{{just_executable()}} --list

sync:
	uv sync --frozen --all-groups

lock:
	uv lock --check

build:
	uv build

test:
	uv run --no-sync pytest

lint:
	uv run --no-sync ruff check

lint-fix:
	uv run --no-sync ruff check --fix

format:
	uv run --no-sync ruff format --check

format-fix:
	uv run --no-sync ruff format

typecheck:
	uv run --no-sync ty check

typecheck-fix:
	uv run --no-sync ty check --fix

docs:
	uv run --group docs --no-sync mkdocs build

docs-serve:
	uv run --group docs --no-sync mkdocs serve
