/* @generated by ptfkit-codegen; DO NOT EDIT. */

#ifdef IMPORT_UMBRELLA
import ptfkit;
#else
import ptfkit.mayr1999;
#endif

#include "close_enough.h"
#include <type_traits>

int main() {
    {
        const auto result = ptfkit::mayr1999::calc_ptf_mayr1999(40.0, 40.0, 20.0, 1.3, 2.0);
        static_assert(std::is_same_v<std::remove_cv_t<decltype(result)>,
                                     ptfkit::mayr1999::Mayr1999PTFResult>);
        assert_in_interval(result.a_hc, 9.1992278257841, 9.199227825784327);
        assert_in_interval(result.b_hc, 8.524324437854638, 8.524324437854865);
        assert_in_interval(result.theta_s, 0.4873316133299964, 0.4873316133300035);
    }
    {
        const auto result = ptfkit::mayr1999::calc_ptf_mayr1999(20.0, 20.0, 60.0, 1.2, 2.0);
        static_assert(std::is_same_v<std::remove_cv_t<decltype(result)>,
                                     ptfkit::mayr1999::Mayr1999PTFResult>);
        assert_in_interval(result.a_hc, 14.530513764091008, 14.530513764091236);
        assert_in_interval(result.b_hc, 18.937514119092267, 18.93751411909272);
        assert_in_interval(result.theta_s, 0.521456841619993, 0.5214568416200072);
    }
    {
        const auto result = ptfkit::mayr1999::calc_ptf_mayr1999(90.0, 5.0, 5.0, 1.5, 1.0);
        static_assert(std::is_same_v<std::remove_cv_t<decltype(result)>,
                                     ptfkit::mayr1999::Mayr1999PTFResult>);
        assert_in_interval(result.a_hc, 2.402166995503591, 2.4021669955036478);
        assert_in_interval(result.b_hc, 3.2690464531590697, 3.2690464531591266);
        assert_in_interval(result.theta_s, 0.4209756914999965, 0.4209756915000036);
    }
    return 0;
}
